"use client";

import { useState } from "react";
import type { AgentVendorReport, ReportType } from "@/types/agent";
import { REPORT_TYPES } from "@/types/agent";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatLabel(value: string): string {
  return value
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

// ---------------------------------------------------------------------------
// Printable Report View
// ---------------------------------------------------------------------------

function PrintableReport(
  props: Readonly<{ report: AgentVendorReport }>
) {
  const { report } = props;
  const data = report.data as Record<string, unknown>;

  return (
    <div className="print:block p-8 bg-white dark:bg-gray-900 rounded-xl border dark:border-gray-700">
      {/* Letterhead */}
      <div className="border-b pb-4 mb-6 dark:border-gray-700">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded bg-blue-600 flex items-center justify-center text-white font-bold text-lg">
            B
          </div>
          <div>
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">
              Britestate Agency
            </h2>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              Vendor Report
            </p>
          </div>
        </div>
      </div>

      {/* Property Details */}
      <section className="mb-6">
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 uppercase tracking-wider mb-2">
          Property Details
        </h3>
        <div className="grid grid-cols-2 gap-3 text-sm">
          <div>
            <span className="text-gray-500 dark:text-gray-400">Property ID:</span>{" "}
            <span className="text-gray-900 dark:text-gray-100">
              {report.property_id ?? "N/A"}
            </span>
          </div>
          <div>
            <span className="text-gray-500 dark:text-gray-400">Report Type:</span>{" "}
            <span className="text-gray-900 dark:text-gray-100">
              {formatLabel(report.report_type)}
            </span>
          </div>
          <div>
            <span className="text-gray-500 dark:text-gray-400">Generated:</span>{" "}
            <span className="text-gray-900 dark:text-gray-100">
              {formatDate(report.generated_at)}
            </span>
          </div>
        </div>
      </section>

      {/* Performance Metrics */}
      <section className="mb-6">
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 uppercase tracking-wider mb-2">
          Performance Metrics
        </h3>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <MetricCard
            label="Total Viewings"
            value={String(data.total_viewings ?? 0)}
          />
          <MetricCard
            label="Booked Viewings"
            value={String(data.booked_viewings ?? 0)}
          />
          <MetricCard
            label="Total Offers"
            value={String(data.total_offers ?? 0)}
          />
          <MetricCard
            label="Time on Market"
            value={data.time_on_market ? `${data.time_on_market}d` : "N/A"}
          />
        </div>
      </section>

      {/* Footer */}
      <div className="border-t pt-4 dark:border-gray-700 text-xs text-gray-400 dark:text-gray-500">
        Report ID: {report.id} | Generated by Britestate
      </div>
    </div>
  );
}

function MetricCard(
  props: Readonly<{ label: string; value: string }>
) {
  return (
    <div className="rounded-lg border p-3 text-center dark:border-gray-700">
      <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">
        {props.value}
      </p>
      <p className="text-xs text-gray-500 dark:text-gray-400">{props.label}</p>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export function VendorReportPDF(
  props: Readonly<{ initialReports: AgentVendorReport[] }>
) {
  const { initialReports } = props;
  const [reports, setReports] = useState(initialReports);
  const [selectedReport, setSelectedReport] = useState<AgentVendorReport | null>(null);
  const [generating, setGenerating] = useState(false);
  const [propertyId, setPropertyId] = useState("");
  const [reportType, setReportType] = useState<ReportType>("listing_performance");
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!propertyId.trim()) {
      setError("Property ID is required");
      return;
    }

    setGenerating(true);
    setError(null);

    try {
      const res = await fetch("/api/agent/reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          property_id: propertyId.trim(),
          report_type: reportType,
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error ?? "Failed to generate report");
      }

      const data = await res.json();
      const newReport = data.report as AgentVendorReport;
      setReports((prev) => [newReport, ...prev]);
      setSelectedReport(newReport);
      setPropertyId("");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setGenerating(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-gray-100">
          Vendor Reports
        </h1>
        <p className="text-sm text-gray-500 dark:text-gray-400">
          Generate and view property performance reports for vendors.
        </p>
      </div>

      {/* Generate form */}
      <div className="rounded-xl border bg-white dark:bg-gray-900 dark:border-gray-700 p-4">
        <h2 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">
          Generate New Report
        </h2>
        {error && (
          <p className="text-sm text-red-600 mb-3">{error}</p>
        )}
        <div className="flex flex-col sm:flex-row gap-3">
          <input
            type="text"
            value={propertyId}
            onChange={(e) => setPropertyId(e.target.value)}
            placeholder="Property ID"
            className="flex-1 rounded-md border px-3 py-2 text-sm dark:bg-gray-800 dark:border-gray-600 dark:text-gray-100"
          />
          <select
            value={reportType}
            onChange={(e) => setReportType(e.target.value as ReportType)}
            className="rounded-md border px-3 py-2 text-sm dark:bg-gray-800 dark:border-gray-600 dark:text-gray-100"
          >
            {REPORT_TYPES.map((rt) => (
              <option key={rt} value={rt}>
                {formatLabel(rt)}
              </option>
            ))}
          </select>
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="shrink-0 rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"
          >
            {generating ? "Generating..." : "Generate Report"}
          </button>
        </div>
      </div>

      {/* Selected report view */}
      {selectedReport && (
        <div className="space-y-3">
          <div className="flex justify-end print:hidden">
            <button
              onClick={handlePrint}
              className="rounded-md border px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-800"
            >
              Print Report
            </button>
          </div>
          <PrintableReport report={selectedReport} />
        </div>
      )}

      {/* Reports list */}
      <div className="rounded-xl border bg-white dark:bg-gray-900 dark:border-gray-700">
        <div className="px-4 py-3 border-b dark:border-gray-700">
          <h2 className="text-sm font-semibold text-gray-700 dark:text-gray-300">
            Previous Reports ({reports.length})
          </h2>
        </div>
        {reports.length === 0 ? (
          <p className="p-4 text-sm text-gray-500 dark:text-gray-400">
            No reports generated yet.
          </p>
        ) : (
          <ul className="divide-y dark:divide-gray-700">
            {reports.map((report) => (
              <li key={report.id}>
                <button
                  onClick={() => setSelectedReport(report)}
                  className="w-full text-left px-4 py-3 hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
                >
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-sm font-medium text-gray-900 dark:text-gray-100">
                        {formatLabel(report.report_type)}
                      </p>
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        Property: {report.property_id ?? "N/A"}
                      </p>
                    </div>
                    <span className="text-xs text-gray-400 dark:text-gray-500">
                      {formatDate(report.generated_at)}
                    </span>
                  </div>
                </button>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
