"use client";

import { useState, useCallback } from "react";
import type { AgentVendorReport, ReportType } from "@/types/agent";
import { REPORT_TYPES } from "@/types/agent";

// ---------------------------------------------------------------------------
// Toast (inline — no external dependency required)
// ---------------------------------------------------------------------------

type ToastState = Readonly<{
  message: string;
  variant: "success" | "error";
}> | null;

function Toast(props: Readonly<{ toast: ToastState; onDismiss: () => void }>) {
  if (!props.toast) return null;

  const bg =
    props.toast.variant === "success"
      ? "bg-green-50 border-green-300 text-green-800 dark:bg-green-900/30 dark:border-green-700 dark:text-green-300"
      : "bg-red-50 border-red-300 text-red-800 dark:bg-red-900/30 dark:border-red-700 dark:text-red-300";

  return (
    <div
      role="alert"
      className={`fixed bottom-4 right-4 z-50 flex items-center gap-3 rounded-lg border px-4 py-3 text-sm shadow-lg ${bg}`}
    >
      <span>{props.toast.message}</span>
      <button
        onClick={props.onDismiss}
        aria-label="Dismiss"
        className="ml-2 opacity-60 hover:opacity-100 transition-opacity"
      >
        &#x2715;
      </button>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatLabel(value: string): string {
  return value
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

// ---------------------------------------------------------------------------
// Printable Report View
// ---------------------------------------------------------------------------

function PrintableReport(
  props: Readonly<{ report: AgentVendorReport }>
) {
  const { report } = props;
  const data = report.data as Record<string, unknown>;

  return (
    <div className="print:block p-8 bg-white dark:bg-gray-900 rounded-xl border dark:border-gray-700">
      {/* Letterhead */}
      <div className="border-b pb-4 mb-6 dark:border-gray-700">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded bg-blue-600 flex items-center justify-center text-white font-bold text-lg">
            B
          </div>
          <div>
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">
              Britestate Agency
            </h2>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              Vendor Report
            </p>
          </div>
        </div>
      </div>

      {/* Property Details */}
      <section className="mb-6">
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 uppercase tracking-wider mb-2">
          Property Details
        </h3>
        <div className="grid grid-cols-2 gap-3 text-sm">
          <div>
            <span className="text-gray-500 dark:text-gray-400">Property ID:</span>{" "}
            <span className="text-gray-900 dark:text-gray-100">
              {report.property_id ?? "N/A"}
            </span>
          </div>
          <div>
            <span className="text-gray-500 dark:text-gray-400">Report Type:</span>{" "}
            <span className="text-gray-900 dark:text-gray-100">
              {formatLabel(report.report_type)}
            </span>
          </div>
          <div>
            <span className="text-gray-500 dark:text-gray-400">Generated:</span>{" "}
            <span className="text-gray-900 dark:text-gray-100">
              {formatDate(report.generated_at)}
            </span>
          </div>
        </div>
      </section>

      {/* Performance Metrics */}
      <section className="mb-6">
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 uppercase tracking-wider mb-2">
          Performance Metrics
        </h3>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <MetricCard
            label="Total Viewings"
            value={String(data.total_viewings ?? 0)}
          />
          <MetricCard
            label="Booked Viewings"
            value={String(data.booked_viewings ?? 0)}
          />
          <MetricCard
            label="Total Offers"
            value={String(data.total_offers ?? 0)}
          />
          <MetricCard
            label="Time on Market"
            value={data.time_on_market ? `${data.time_on_market}d` : "N/A"}
          />
        </div>
      </section>

      {/* Footer */}
      <div className="border-t pt-4 dark:border-gray-700 text-xs text-gray-400 dark:text-gray-500">
        Report ID: {report.id} | Generated by Britestate
      </div>
    </div>
  );
}

function MetricCard(
  props: Readonly<{ label: string; value: string }>
) {
  return (
    <div className="rounded-lg border p-3 text-center dark:border-gray-700">
      <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">
        {props.value}
      </p>
      <p className="text-xs text-gray-500 dark:text-gray-400">{props.label}</p>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export function VendorReportPDF(
  props: Readonly<{ initialReports: AgentVendorReport[] }>
) {
  const { initialReports } = props;
  const [reports, setReports] = useState(initialReports);
  const [selectedReport, setSelectedReport] = useState<AgentVendorReport | null>(null);
  const [generating, setGenerating] = useState(false);
  const [propertyId, setPropertyId] = useState("");
  const [reportType, setReportType] = useState<ReportType>("listing_performance");
  const [error, setError] = useState<string | null>(null);

  // Send-to-vendor state
  // TODO: When the property→seller relationship is modelled in the DB,
  // resolve vendorEmail automatically from the selected report's property_id
  // instead of requiring the agent to enter it manually.
  const [vendorEmail, setVendorEmail] = useState("vendor@example.com");
  const [isSending, setIsSending] = useState(false);
  const [toast, setToast] = useState<ToastState>(null);

  const dismissToast = useCallback(() => setToast(null), []);

  const handleSendToVendor = useCallback(async () => {
    if (!selectedReport) return;

    setIsSending(true);
    setToast(null);

    try {
      const res = await fetch("/api/agent/reports/send", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          report_id: selectedReport.id,
          vendor_email: vendorEmail,
        }),
      });

      if (!res.ok) {
        const data = (await res.json()) as { error?: string };
        throw new Error(data.error ?? "Failed to send report");
      }

      setToast({ message: "Report sent to vendor", variant: "success" });
    } catch (err) {
      const message =
        err instanceof Error ? err.message : "Failed to send report";
      setToast({ message, variant: "error" });
    } finally {
      setIsSending(false);
    }
  }, [selectedReport, vendorEmail]);

  const handleGenerate = async () => {
    if (!propertyId.trim()) {
      setError("Property ID is required");
      return;
    }

    setGenerating(true);
    setError(null);

    try {
      const res = await fetch("/api/agent/reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          property_id: propertyId.trim(),
          report_type: reportType,
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error ?? "Failed to generate report");
      }

      const data = await res.json();
      const newReport = data.report as AgentVendorReport;
      setReports((prev) => [newReport, ...prev]);
      setSelectedReport(newReport);
      setPropertyId("");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setGenerating(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      <Toast toast={toast} onDismiss={dismissToast} />

      <div>
        <h1 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-gray-100">
          Vendor Reports
        </h1>
        <p className="text-sm text-gray-500 dark:text-gray-400">
          Generate and view property performance reports for vendors.
        </p>
      </div>

      {/* Generate form */}
      <div className="rounded-xl border bg-white dark:bg-gray-900 dark:border-gray-700 p-4">
        <h2 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">
          Generate New Report
        </h2>
        {error && (
          <p className="text-sm text-red-600 mb-3">{error}</p>
        )}
        <div className="flex flex-col sm:flex-row gap-3">
          <input
            type="text"
            value={propertyId}
            onChange={(e) => setPropertyId(e.target.value)}
            placeholder="Property ID"
            className="flex-1 rounded-md border px-3 py-2 text-sm dark:bg-gray-800 dark:border-gray-600 dark:text-gray-100"
          />
          <select
            value={reportType}
            onChange={(e) => setReportType(e.target.value as ReportType)}
            className="rounded-md border px-3 py-2 text-sm dark:bg-gray-800 dark:border-gray-600 dark:text-gray-100"
          >
            {REPORT_TYPES.map((rt) => (
              <option key={rt} value={rt}>
                {formatLabel(rt)}
              </option>
            ))}
          </select>
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="shrink-0 rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"
          >
            {generating ? "Generating..." : "Generate Report"}
          </button>
        </div>
      </div>

      {/* Selected report view */}
      {selectedReport && (
        <div className="space-y-3">
          <div className="flex flex-wrap items-center gap-3 justify-end print:hidden">
            {/* Vendor email input + send button */}
            {/* TODO: auto-resolve vendor email from property_id once the
                property→seller relationship is modelled in the DB */}
            <input
              type="email"
              value={vendorEmail}
              onChange={(e) => setVendorEmail(e.target.value)}
              placeholder="Vendor email address"
              aria-label="Vendor email address"
              className="rounded-md border px-3 py-2 text-sm dark:bg-gray-800 dark:border-gray-600 dark:text-gray-100 w-56"
            />
            <button
              onClick={handleSendToVendor}
              disabled={isSending || !vendorEmail.trim()}
              className="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              {isSending ? "Sending..." : "Send to vendor now"}
            </button>
            <button
              onClick={handlePrint}
              className="rounded-md border px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-800"
            >
              Print Report
            </button>
          </div>
          <PrintableReport report={selectedReport} />
        </div>
      )}

      {/* Reports list */}
      <div className="rounded-xl border bg-white dark:bg-gray-900 dark:border-gray-700">
        <div className="px-4 py-3 border-b dark:border-gray-700">
          <h2 className="text-sm font-semibold text-gray-700 dark:text-gray-300">
            Previous Reports ({reports.length})
          </h2>
        </div>
        {reports.length === 0 ? (
          <p className="p-4 text-sm text-gray-500 dark:text-gray-400">
            No reports generated yet.
          </p>
        ) : (
          <ul className="divide-y dark:divide-gray-700">
            {reports.map((report) => (
              <li key={report.id}>
                <button
                  onClick={() => setSelectedReport(report)}
                  className="w-full text-left px-4 py-3 hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
                >
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-sm font-medium text-gray-900 dark:text-gray-100">
                        {formatLabel(report.report_type)}
                      </p>
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        Property: {report.property_id ?? "N/A"}
                      </p>
                    </div>
                    <span className="text-xs text-gray-400 dark:text-gray-500">
                      {formatDate(report.generated_at)}
                    </span>
                  </div>
                </button>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
