/* eslint-disable no-console -- TODO Sprint 1: migrate console.error to captureException */
/**
 * GET /api/market-map/tiles/[z]/[x]/[y]
 *
 * Returns a Mapbox Vector Tile (protobuf, layer `areas`) for the z/x/y tile,
 * generated by the `market_map_tile` RPC. Responses are immutable-cached: the
 * client appends `?v=<data_version>` so a precompute rebuild yields new URLs
 * and busts the year-long edge cache.
 *
 * Path params:
 *   z  zoom level (0..22)
 *   x  tile column
 *   y  tile row (a ".mvt"/".pbf" extension is stripped if present)
 *
 * Query params (all optional):
 *   property_type  all|detached|semi-detached|terraced|flat (default: all)
 *   window         rolling-window months (default 12)
 *   v              data-version cache buster (accepted and ignored here)
 */

import { NextRequest } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { decodeByteaToBuffer } from "@/services/market-map/tile-service";

const MAX_ZOOM = 22;
const DEFAULT_WINDOW = 12;

/**
 * Parse a tile coordinate segment to an integer, stripping any file extension
 * (e.g. "660.mvt" -> 660). Returns null when the segment is not a clean int.
 */
function parseTileCoord(raw: string): number | null {
  const stripped = raw.split(".")[0];
  if (!/^-?\d+$/.test(stripped)) return null;
  const n = Number(stripped);
  return Number.isInteger(n) ? n : null;
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ z: string; x: string; y: string }> },
): Promise<Response> {
  const { z: zRaw, x: xRaw, y: yRaw } = await params;

  const z = parseTileCoord(zRaw);
  const x = parseTileCoord(xRaw);
  const y = parseTileCoord(yRaw);

  if (z === null || x === null || y === null) {
    return new Response("Invalid tile coordinates", { status: 400 });
  }

  if (z < 0 || z > MAX_ZOOM) {
    return new Response("Zoom out of range", { status: 400 });
  }

  // Tile column/row must fit within the 2^z grid for the requested zoom.
  const maxIndex = 2 ** z - 1;
  if (x < 0 || x > maxIndex || y < 0 || y > maxIndex) {
    return new Response("Tile coordinates out of range", { status: 400 });
  }

  const { searchParams } = request.nextUrl;
  const propertyType = searchParams.get("property_type") ?? "all";
  const windowRaw = searchParams.get("window");
  const windowParsed = windowRaw === null ? DEFAULT_WINDOW : Number.parseInt(windowRaw, 10);
  const windowMonths = Number.isInteger(windowParsed) ? windowParsed : DEFAULT_WINDOW;

  const supabase = createAdminClient();
  const { data, error } = await supabase.rpc("market_map_tile", {
    p_z: z,
    p_x: x,
    p_y: y,
    p_property_type: propertyType,
    p_window: windowMonths,
  });

  if (error) {
    console.error("[market-map-tiles] RPC error:", error);
    return new Response("Failed to generate tile", { status: 500 });
  }

  const buffer = decodeByteaToBuffer(typeof data === "string" ? data : null);
  if (buffer === null) {
    return new Response(null, { status: 204 });
  }

  // Buffer is a Uint8Array subclass; pass a plain view to satisfy the web
  // `BodyInit` type (the runtime streams the same bytes).
  return new Response(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/vnd.mapbox-vector-tile",
      "Cache-Control": "public, max-age=31536000, immutable",
    },
  });
}
