import type { Metadata } from "next";
import { SITE_URL } from "@/lib/seo/config";

/**
 * Root-level metadata defaults.
 *
 * Extracted into its own module so the shape can be unit-tested without
 * pulling in next/font/google (which is a Next.js build-time API and fails
 * under Vitest).
 *
 * metadataBase is critical: without it, relative OG image paths generated by
 * child pages are broken in social share previews.
 */
export const rootMetadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "Britestate | UK Property Portal",
  description:
    "Find your perfect UK property. Search, compare, and transact with AI-powered matching, verified agents, and trusted tradespeople.",
  openGraph: {
    siteName: "Britestate",
    locale: "en_GB",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    site: "@britestate",
  },
};
