import type { NeighbourhoodData } from "@/types/areas";

const data: Record<string, NeighbourhoodData> = {
  "london/islington": {
    slug: "islington",
    name: "Islington",
    citySlug: "london",
    cityName: "London",
    borough: "London Borough of Islington",
    postcode: "N1",
    description: "Islington is a vibrant inner-London neighbourhood known for its Georgian terraces, thriving restaurant scene on Upper Street, and strong arts culture. It blends long-established working-class roots with a now-dominant professional demographic drawn by excellent transport links and proximity to the City.",
    coordinates: { lat: 51.5362, lng: -0.1033 },
    avgPrice: 740000,
    avgPriceFormatted: "£740,000",
    yoyChange: "+3.1%",
    greenSpace: "18%",
    walkability: "High",
    noiseLevel: "Busy",
    demographics: { topGroup: "Young Professionals", medianAge: 34, ownerOccupied: 31, privateRented: 52, socialRented: 17, vibe: "Cosmopolitan & creative" },
    schools: [
      { name: "Thornhill Primary School", ofsted: "Outstanding", distance: "0.3 mi", type: "Primary" },
      { name: "Elizabeth Garrett Anderson School", ofsted: "Outstanding", distance: "0.5 mi", type: "Secondary" },
      { name: "St Mary Magdalene Academy", ofsted: "Good", distance: "0.7 mi", type: "All-through" },
    ],
    localFavourites: [
      { label: "Highbury Fields", desc: "47-acre park with tennis courts and an open-air pool", category: "park" },
      { label: "Ottolenghi", desc: "Iconic deli and restaurant on Upper Street", category: "cafe" },
      { label: "The Compton Arms", desc: "Tucked-away Victorian pub beloved by locals", category: "pub" },
    ],
    propertyMix: { D: 5, S: 8, T: 22, F: 62, O: 3 },
    broadband: { download: 220, upload: 48, coverage5g: true },
    crimeIndex: { local: 112, borough: 98, city: 87 },
    agent: { name: "Sophie Marchetti", role: "Area Specialist", quote: "Islington sells fast — well-presented flats regularly go above asking within days.", initials: "SM" },
    transportLinks: [
      { name: "Angel", type: "underground", detail: "Northern line — 10 min to Bank", emoji: "🚇" },
      { name: "Highbury & Islington", type: "underground", detail: "Victoria line & Overground", emoji: "🚇" },
    ],
  },
  "london/camden": {
    slug: "camden",
    name: "Camden",
    citySlug: "london",
    cityName: "London",
    borough: "London Borough of Camden",
    postcode: "NW1",
    description: "Camden is London's most eclectic neighbourhood, famous for its market, music heritage and canal-side walks. The housing stock ranges from Victorian villas in Primrose Hill to converted warehouse flats near the Lock, attracting a mix of creatives, families and young professionals.",
    coordinates: { lat: 51.5390, lng: -0.1426 },
    avgPrice: 820000,
    avgPriceFormatted: "£820,000",
    yoyChange: "+2.8%",
    greenSpace: "22%",
    walkability: "High",
    noiseLevel: "Busy",
    demographics: { topGroup: "Creatives & Professionals", medianAge: 33, ownerOccupied: 34, privateRented: 48, socialRented: 18, vibe: "Bohemian & eclectic" },
    schools: [
      { name: "Primrose Hill Primary School", ofsted: "Outstanding", distance: "0.4 mi", type: "Primary" },
      { name: "Haverstock School", ofsted: "Good", distance: "0.6 mi", type: "Secondary" },
      { name: "La Sainte Union Catholic School", ofsted: "Good", distance: "0.9 mi", type: "Secondary" },
    ],
    localFavourites: [
      { label: "Regent's Canal towpath", desc: "Peaceful walking and cycling route to Little Venice", category: "park" },
      { label: "Camden Market", desc: "400+ stalls of street food, vintage and craft", category: "attraction" },
      { label: "The Hawley Arms", desc: "Indie pub with live music and a loyal local following", category: "pub" },
    ],
    propertyMix: { D: 8, S: 10, T: 25, F: 54, O: 3 },
    broadband: { download: 240, upload: 52, coverage5g: true },
    crimeIndex: { local: 125, borough: 105, city: 87 },
    agent: { name: "Tom Fairweather", role: "Senior Negotiator", quote: "Canal-side conversions are always our fastest movers — buyers come from across London.", initials: "TF" },
    transportLinks: [
      { name: "Camden Town", type: "underground", detail: "Northern line — 12 min to King's Cross", emoji: "🚇" },
      { name: "Chalk Farm", type: "underground", detail: "Northern line — quieter entry point", emoji: "🚇" },
    ],
  },
  "london/isleworth": {
    slug: "isleworth",
    name: "Isleworth",
    citySlug: "london",
    cityName: "London",
    borough: "London Borough of Hounslow",
    postcode: "TW7",
    description: "Isleworth is a leafy Thames-side suburb in west London offering excellent value compared to its Richmond neighbours. The area features handsome Edwardian semis, good schools and a charming village core around All Saints Church and the Duke of Northumberland's River.",
    coordinates: { lat: 51.4674, lng: -0.3340 },
    avgPrice: 520000,
    avgPriceFormatted: "£520,000",
    yoyChange: "+4.5%",
    greenSpace: "35%",
    walkability: "Medium",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Families", medianAge: 38, ownerOccupied: 55, privateRented: 34, socialRented: 11, vibe: "Suburban & family-friendly" },
    schools: [
      { name: "Isleworth & Syon School", ofsted: "Good", distance: "0.5 mi", type: "Secondary" },
      { name: "St Mary's Catholic Primary", ofsted: "Outstanding", distance: "0.3 mi", type: "Primary" },
      { name: "Spring Grove Primary School", ofsted: "Good", distance: "0.6 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Syon Park", desc: "200-acre grounds with a garden centre and butterfly house", category: "park" },
      { label: "London Apprentice", desc: "Historic riverside pub dating to the 15th century", category: "pub" },
      { label: "Isleworth Farmers' Market", desc: "Weekly market with local produce and artisan goods", category: "shop" },
    ],
    propertyMix: { D: 15, S: 38, T: 30, F: 15, O: 2 },
    broadband: { download: 185, upload: 38, coverage5g: true },
    crimeIndex: { local: 62, borough: 71, city: 87 },
    agent: { name: "Priya Sharma", role: "Residential Director", quote: "Buyers priced out of Richmond find Isleworth offers the same riverside feel at 30% less.", initials: "PS" },
    transportLinks: [
      { name: "Isleworth", type: "rail", detail: "South Western Railway — 30 min to Waterloo", emoji: "🚆" },
      { name: "Osterley", type: "underground", detail: "Piccadilly line — direct to Heathrow", emoji: "🚇" },
    ],
  },
  "london/brixton": {
    slug: "brixton",
    name: "Brixton",
    citySlug: "london",
    cityName: "London",
    borough: "London Borough of Lambeth",
    postcode: "SW9",
    description: "Brixton is one of London's most culturally rich neighbourhoods, home to a world-famous market, vibrant live-music scene and the beloved Electric Avenue. Rapid gentrification has pushed prices up sharply while the area retains its Afro-Caribbean heritage and community spirit.",
    coordinates: { lat: 51.4613, lng: -0.1156 },
    avgPrice: 580000,
    avgPriceFormatted: "£580,000",
    yoyChange: "+5.2%",
    greenSpace: "14%",
    walkability: "High",
    noiseLevel: "Busy",
    demographics: { topGroup: "Young Professionals & Creatives", medianAge: 32, ownerOccupied: 28, privateRented: 54, socialRented: 18, vibe: "Energetic & diverse" },
    schools: [
      { name: "Corpus Christi Catholic Primary", ofsted: "Outstanding", distance: "0.4 mi", type: "Primary" },
      { name: "Brixton Academy Sixth Form", ofsted: "Good", distance: "0.7 mi", type: "Secondary" },
      { name: "Stockwell Primary School", ofsted: "Good", distance: "0.5 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Brockwell Park", desc: "Hilltop park with a lido and panoramic London views", category: "park" },
      { label: "Market Row", desc: "Covered market with independent cafés and eateries", category: "cafe" },
      { label: "The Effra Social", desc: "Relaxed bar with jazz nights and a garden", category: "pub" },
    ],
    propertyMix: { D: 3, S: 6, T: 18, F: 70, O: 3 },
    broadband: { download: 210, upload: 44, coverage5g: true },
    crimeIndex: { local: 118, borough: 102, city: 87 },
    agent: { name: "Marcus Williams", role: "Sales Manager", quote: "Brixton's energy is infectious — buyers who visit rarely look elsewhere.", initials: "MW" },
    transportLinks: [
      { name: "Brixton", type: "underground", detail: "Victoria line — 12 min to Victoria", emoji: "🚇" },
      { name: "Herne Hill", type: "rail", detail: "Thameslink — direct to St Pancras", emoji: "🚆" },
    ],
  },
  "london/greenwich": {
    slug: "greenwich",
    name: "Greenwich",
    citySlug: "london",
    cityName: "London",
    borough: "Royal Borough of Greenwich",
    postcode: "SE10",
    description: "Greenwich combines maritime history, UNESCO World Heritage status and one of London's finest parks. The town centre retains a village feel with independent traders, antique markets and Georgian architecture, while Canary Wharf is a short DLR ride away.",
    coordinates: { lat: 51.4826, lng: -0.0077 },
    avgPrice: 610000,
    avgPriceFormatted: "£610,000",
    yoyChange: "+3.8%",
    greenSpace: "28%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Professionals & Families", medianAge: 36, ownerOccupied: 42, privateRented: 42, socialRented: 16, vibe: "Historic & aspirational" },
    schools: [
      { name: "Maze Hill Primary School", ofsted: "Outstanding", distance: "0.4 mi", type: "Primary" },
      { name: "Thomas Tallis School", ofsted: "Good", distance: "0.8 mi", type: "All-through" },
      { name: "St Ursula's Convent School", ofsted: "Good", distance: "1.0 mi", type: "Secondary" },
    ],
    localFavourites: [
      { label: "Greenwich Park", desc: "183-acre Royal Park with the Observatory and city views", category: "park" },
      { label: "Cutty Sark", desc: "Victorian tea clipper and maritime museum", category: "attraction" },
      { label: "The Gipsy Moth", desc: "Wetherspoon by the river with a sunny terrace", category: "pub" },
    ],
    propertyMix: { D: 12, S: 15, T: 28, F: 42, O: 3 },
    broadband: { download: 195, upload: 40, coverage5g: true },
    crimeIndex: { local: 78, borough: 82, city: 87 },
    agent: { name: "Claire Hennessy", role: "Area Director", quote: "The park, the DLR, the history — Greenwich sells itself to every buyer demographic.", initials: "CH" },
    transportLinks: [
      { name: "Greenwich DLR", type: "rail", detail: "DLR — 12 min to Canary Wharf", emoji: "🚆" },
      { name: "Cutty Sark DLR", type: "rail", detail: "DLR — tourist and commuter route", emoji: "🚆" },
    ],
  },
  "london/hackney": {
    slug: "hackney",
    name: "Hackney",
    citySlug: "london",
    cityName: "London",
    borough: "London Borough of Hackney",
    postcode: "E8",
    description: "Hackney has undergone one of London's most dramatic transformations, evolving from an overlooked area into one of its most sought-after postcodes. Independent coffee shops, street art, Broadway Market and London Fields define a neighbourhood that attracts creatives and tech professionals alike.",
    coordinates: { lat: 51.5450, lng: -0.0553 },
    avgPrice: 660000,
    avgPriceFormatted: "£660,000",
    yoyChange: "+4.1%",
    greenSpace: "20%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Creatives & Tech Workers", medianAge: 32, ownerOccupied: 30, privateRented: 55, socialRented: 15, vibe: "Hipster & community-driven" },
    schools: [
      { name: "London Fields Primary School", ofsted: "Good", distance: "0.3 mi", type: "Primary" },
      { name: "Hackney New School", ofsted: "Outstanding", distance: "0.6 mi", type: "Secondary" },
      { name: "St John & St James CE Primary", ofsted: "Good", distance: "0.5 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "London Fields Lido", desc: "Heated outdoor pool open year-round", category: "attraction" },
      { label: "Broadway Market", desc: "Saturday market with top-tier street food and producers", category: "shop" },
      { label: "Netil Market", desc: "Artisan weekend market in a converted yard", category: "cafe" },
    ],
    propertyMix: { D: 4, S: 7, T: 20, F: 66, O: 3 },
    broadband: { download: 230, upload: 50, coverage5g: true },
    crimeIndex: { local: 105, borough: 110, city: 87 },
    agent: { name: "Zoe Kavanagh", role: "Lead Negotiator", quote: "Hackney buyers are loyal — once they've lived here they rarely leave the postcode.", initials: "ZK" },
    transportLinks: [
      { name: "London Fields", type: "rail", detail: "Overground — 8 min to Shoreditch High St", emoji: "🚆" },
      { name: "Hackney Central", type: "rail", detail: "Overground — direct to Stratford", emoji: "🚆" },
    ],
  },

  // Manchester
  "manchester/ancoats": {
    slug: "ancoats",
    name: "Ancoats",
    citySlug: "manchester",
    cityName: "Manchester",
    borough: "Manchester City Centre",
    postcode: "M4",
    description: "Ancoats was the world's first industrial suburb and is now Manchester's most talked-about neighbourhood. Converted mills, independent restaurants and craft breweries draw young professionals, while the ongoing Ancoats regeneration continues to deliver new apartments and green squares.",
    coordinates: { lat: 53.4839, lng: -2.2254 },
    avgPrice: 295000,
    avgPriceFormatted: "£295,000",
    yoyChange: "+6.8%",
    greenSpace: "12%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Young Professionals", medianAge: 29, ownerOccupied: 22, privateRented: 72, socialRented: 6, vibe: "Industrial-chic & buzzing" },
    schools: [
      { name: "St Anne's RC Primary School", ofsted: "Good", distance: "0.5 mi", type: "Primary" },
      { name: "Manchester Academy", ofsted: "Good", distance: "0.9 mi", type: "All-through" },
      { name: "Ancoats & Clayton Academy", ofsted: "Requires Improvement", distance: "0.7 mi", type: "Secondary" },
    ],
    localFavourites: [
      { label: "Cutting Room Square", desc: "Lively piazza surrounded by bars and restaurants", category: "attraction" },
      { label: "Elnecot", desc: "Critically acclaimed modern British restaurant in a mill", category: "cafe" },
      { label: "Cloudwater Brew Co", desc: "Pioneering craft brewery with a popular tap room", category: "pub" },
    ],
    propertyMix: { D: 1, S: 2, T: 5, F: 90, O: 2 },
    broadband: { download: 260, upload: 60, coverage5g: true },
    crimeIndex: { local: 95, borough: 88, city: 72 },
    agent: { name: "Dan Whitfield", role: "City Centre Specialist", quote: "Ancoats is Manchester's hottest postcode — new-build penthouses sell off-plan within hours.", initials: "DW" },
    transportLinks: [
      { name: "Manchester Piccadilly", type: "rail", detail: "10 min walk — national rail and Metrolink", emoji: "🚆" },
      { name: "New Islington Metrolink", type: "tram", detail: "Metrolink — direct to MediaCityUK", emoji: "🚊" },
    ],
  },
  "manchester/didsbury": {
    slug: "didsbury",
    name: "Didsbury",
    citySlug: "manchester",
    cityName: "Manchester",
    borough: "Didsbury & Withington",
    postcode: "M20",
    description: "Didsbury is Manchester's most prestigious suburb, renowned for its tree-lined avenues, excellent schools and vibrant village atmosphere. Large Victorian villas and Edwardian semis attract established families and senior professionals who want suburban calm with swift city-centre access.",
    coordinates: { lat: 53.4141, lng: -2.2299 },
    avgPrice: 480000,
    avgPriceFormatted: "£480,000",
    yoyChange: "+4.2%",
    greenSpace: "38%",
    walkability: "Medium",
    noiseLevel: "Quiet",
    demographics: { topGroup: "Affluent Families", medianAge: 42, ownerOccupied: 65, privateRented: 28, socialRented: 7, vibe: "Leafy & aspirational" },
    schools: [
      { name: "Didsbury CE Primary School", ofsted: "Outstanding", distance: "0.3 mi", type: "Primary" },
      { name: "Parrs Wood High School", ofsted: "Good", distance: "0.6 mi", type: "Secondary" },
      { name: "Beaver Road Primary School", ofsted: "Outstanding", distance: "0.5 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Fletcher Moss Park", desc: "Tranquil botanical gardens along the River Mersey", category: "park" },
      { label: "Epicerie Ludo", desc: "French deli and café on Lapwing Lane", category: "cafe" },
      { label: "The Metropolitan", desc: "Victorian corner pub with real ales and live sport", category: "pub" },
    ],
    propertyMix: { D: 32, S: 28, T: 18, F: 20, O: 2 },
    broadband: { download: 210, upload: 45, coverage5g: true },
    crimeIndex: { local: 38, borough: 52, city: 72 },
    agent: { name: "Helen Crossley", role: "Residential Partner", quote: "Didsbury detacheds rarely come to market — when they do, expect multiple best offers.", initials: "HC" },
    transportLinks: [
      { name: "East Didsbury Metrolink", type: "tram", detail: "Metrolink — 25 min to Manchester city centre", emoji: "🚊" },
      { name: "Didsbury Village Metrolink", type: "tram", detail: "Metrolink — Airport line", emoji: "🚊" },
    ],
  },
  "manchester/chorlton": {
    slug: "chorlton",
    name: "Chorlton",
    citySlug: "manchester",
    cityName: "Manchester",
    borough: "Chorlton & Whalley Range",
    postcode: "M21",
    description: "Chorlton is Manchester's bohemian heartland — a neighbourhood of independent delis, real-ale pubs and progressive politics. Popular with young families, artists and academics, it combines Victorian terraces with Chorlton Water Park and some of the city's best brunch spots.",
    coordinates: { lat: 53.4393, lng: -2.2720 },
    avgPrice: 360000,
    avgPriceFormatted: "£360,000",
    yoyChange: "+5.0%",
    greenSpace: "30%",
    walkability: "Medium",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Young Families & Creatives", medianAge: 35, ownerOccupied: 52, privateRented: 40, socialRented: 8, vibe: "Alternative & community-minded" },
    schools: [
      { name: "Chorlton CofE Primary", ofsted: "Good", distance: "0.4 mi", type: "Primary" },
      { name: "Chorlton High School", ofsted: "Good", distance: "0.5 mi", type: "Secondary" },
      { name: "St Clement's RC Primary", ofsted: "Outstanding", distance: "0.6 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Chorlton Water Park", desc: "Local nature reserve with a sailing lake", category: "park" },
      { label: "Barbakan Deli", desc: "Legendary Polish bakery and deli open since 1955", category: "shop" },
      { label: "The Beech", desc: "Real-ale pub with a sprawling beer garden", category: "pub" },
    ],
    propertyMix: { D: 10, S: 20, T: 52, F: 16, O: 2 },
    broadband: { download: 195, upload: 42, coverage5g: true },
    crimeIndex: { local: 55, borough: 60, city: 72 },
    agent: { name: "Rachel Booth", role: "Area Manager", quote: "Chorlton buyers have strong local loyalty — most come via word of mouth before we list.", initials: "RB" },
    transportLinks: [
      { name: "St Werburgh's Road Metrolink", type: "tram", detail: "Metrolink — 20 min to city centre", emoji: "🚊" },
      { name: "Manchester Oxford Road", type: "rail", detail: "Bus connections — 25 min ride", emoji: "🚌" },
    ],
  },
  "manchester/northern-quarter": {
    slug: "northern-quarter",
    name: "Northern Quarter",
    citySlug: "manchester",
    cityName: "Manchester",
    borough: "Manchester City Centre",
    postcode: "M4",
    description: "The Northern Quarter is Manchester's creative and cultural hub, packed with independent record shops, street art, cocktail bars and some of the UK's best independent food and music venues. Almost entirely rental, it's the first destination for graduates moving to the city.",
    coordinates: { lat: 53.4838, lng: -2.2348 },
    avgPrice: 265000,
    avgPriceFormatted: "£265,000",
    yoyChange: "+5.5%",
    greenSpace: "8%",
    walkability: "High",
    noiseLevel: "Busy",
    demographics: { topGroup: "Students & Graduates", medianAge: 27, ownerOccupied: 15, privateRented: 80, socialRented: 5, vibe: "Creative & counter-cultural" },
    schools: [
      { name: "St Joseph's RC Primary", ofsted: "Good", distance: "0.6 mi", type: "Primary" },
      { name: "Manchester Communication Academy", ofsted: "Good", distance: "0.9 mi", type: "Secondary" },
      { name: "Sackville Street Building (UMIST)", ofsted: "Outstanding", distance: "0.8 mi", type: "All-through" },
    ],
    localFavourites: [
      { label: "Afflecks Palace", desc: "Four-storey indie emporium with 60+ traders", category: "shop" },
      { label: "Takk Coffee House", desc: "Scandinavian-inspired speciality coffee spot", category: "cafe" },
      { label: "The Castle Hotel", desc: "Intimate live music pub on Oldham Street", category: "pub" },
    ],
    propertyMix: { D: 0, S: 1, T: 3, F: 94, O: 2 },
    broadband: { download: 280, upload: 65, coverage5g: true },
    crimeIndex: { local: 130, borough: 88, city: 72 },
    agent: { name: "Jake Nolan", role: "BTL Specialist", quote: "NQ flats yield 6–7% gross — a reliable income stream despite high tenant turnover.", initials: "JN" },
    transportLinks: [
      { name: "Manchester Piccadilly", type: "rail", detail: "8 min walk — national rail hub", emoji: "🚆" },
      { name: "Shudehill Metrolink", type: "tram", detail: "Metrolink & bus interchange", emoji: "🚊" },
    ],
  },

  // Birmingham
  "birmingham/edgbaston": {
    slug: "edgbaston",
    name: "Edgbaston",
    citySlug: "birmingham",
    cityName: "Birmingham",
    borough: "Edgbaston",
    postcode: "B15",
    description: "Edgbaston is Birmingham's most exclusive residential address, featuring grand Victorian villas on private roads, leafy tree-lined streets and Birmingham's famous Botanical Gardens. Home to the renowned Edgbaston Cricket Ground, the area attracts senior professionals, consultants and established families.",
    coordinates: { lat: 52.4636, lng: -1.9290 },
    avgPrice: 420000,
    avgPriceFormatted: "£420,000",
    yoyChange: "+3.5%",
    greenSpace: "42%",
    walkability: "Medium",
    noiseLevel: "Quiet",
    demographics: { topGroup: "Affluent Professionals", medianAge: 44, ownerOccupied: 62, privateRented: 30, socialRented: 8, vibe: "Refined & established" },
    schools: [
      { name: "Edgbaston High School for Girls", ofsted: "Outstanding", distance: "0.4 mi", type: "Secondary" },
      { name: "St George's CE Primary", ofsted: "Good", distance: "0.5 mi", type: "Primary" },
      { name: "King Edward's School Birmingham", ofsted: "Outstanding", distance: "0.7 mi", type: "Secondary" },
    ],
    localFavourites: [
      { label: "Birmingham Botanical Gardens", desc: "15 acres of glasshouses and ornamental gardens", category: "park" },
      { label: "Edgbaston Cricket Ground", desc: "Test match venue with a renowned hospitality offer", category: "attraction" },
      { label: "The Physician", desc: "Opulent cocktail bar inside a former doctor's surgery", category: "pub" },
    ],
    propertyMix: { D: 38, S: 28, T: 14, F: 18, O: 2 },
    broadband: { download: 200, upload: 42, coverage5g: true },
    crimeIndex: { local: 42, borough: 58, city: 68 },
    agent: { name: "Andrew Pemberton", role: "Director", quote: "Edgbaston's private roads command a significant premium — and demand consistently outstrips supply.", initials: "AP" },
    transportLinks: [
      { name: "Five Ways", type: "rail", detail: "Cross-City line — 5 min to Birmingham New St", emoji: "🚆" },
      { name: "Edgbaston Village", type: "bus", detail: "Regular services to city centre", emoji: "🚌" },
    ],
  },
  "birmingham/jewellery-quarter": {
    slug: "jewellery-quarter",
    name: "Jewellery Quarter",
    citySlug: "birmingham",
    cityName: "Birmingham",
    borough: "Ladywood",
    postcode: "B18",
    description: "The Jewellery Quarter is Birmingham's most rapidly gentrifying district, where Victorian workshops have been converted into loft apartments and artisan studios. The area's rich manufacturing heritage sits alongside a growing restaurant and bar scene, drawing a young professional crowd.",
    coordinates: { lat: 52.4863, lng: -1.9138 },
    avgPrice: 260000,
    avgPriceFormatted: "£260,000",
    yoyChange: "+7.2%",
    greenSpace: "10%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Young Professionals", medianAge: 30, ownerOccupied: 28, privateRented: 68, socialRented: 4, vibe: "Artisan & up-and-coming" },
    schools: [
      { name: "Jewellery Quarter Academy", ofsted: "Good", distance: "0.3 mi", type: "Primary" },
      { name: "Ladywood Arts & Leisure College", ofsted: "Good", distance: "0.7 mi", type: "Secondary" },
      { name: "St Patrick's RC Primary", ofsted: "Good", distance: "0.6 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Museum of the Jewellery Quarter", desc: "Living museum inside a preserved Smith & Pepper factory", category: "attraction" },
      { label: "Tilt", desc: "Acclaimed cocktail bar with a pinball theme", category: "pub" },
      { label: "Burning Soul Brewery", desc: "Local craft brewery with a lively tap room", category: "pub" },
    ],
    propertyMix: { D: 2, S: 3, T: 8, F: 85, O: 2 },
    broadband: { download: 245, upload: 55, coverage5g: true },
    crimeIndex: { local: 88, borough: 75, city: 68 },
    agent: { name: "Lisa Okafor", role: "City Specialist", quote: "JQ loft conversions are unique stock — they don't depreciate and they don't hang around.", initials: "LO" },
    transportLinks: [
      { name: "Jewellery Quarter", type: "rail", detail: "Cross-City line — 3 min to Birmingham New St", emoji: "🚆" },
      { name: "Snow Hill Trams", type: "tram", detail: "West Midlands Metro — city centre tram stop", emoji: "🚊" },
    ],
  },
  "birmingham/moseley": {
    slug: "moseley",
    name: "Moseley",
    citySlug: "birmingham",
    cityName: "Birmingham",
    borough: "Moseley & Kings Heath",
    postcode: "B13",
    description: "Moseley is Birmingham's bohemian village, with a weekly farmers' market, an arts cinema, independent traders and a diverse, progressive community. Victorian and Edwardian terraces attract young families and professionals seeking character properties close to the city.",
    coordinates: { lat: 52.4452, lng: -1.8904 },
    avgPrice: 310000,
    avgPriceFormatted: "£310,000",
    yoyChange: "+4.8%",
    greenSpace: "24%",
    walkability: "Medium",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Young Families & Academics", medianAge: 36, ownerOccupied: 50, privateRented: 42, socialRented: 8, vibe: "Village bohemian" },
    schools: [
      { name: "Moseley Church of England Primary", ofsted: "Good", distance: "0.4 mi", type: "Primary" },
      { name: "Moseley School & Sixth Form", ofsted: "Good", distance: "0.5 mi", type: "Secondary" },
      { name: "St Mary's RC Primary School", ofsted: "Outstanding", distance: "0.6 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Moseley Bog", desc: "Ancient marshland that inspired Tolkien's Middle-earth", category: "park" },
      { label: "Moseley Farmers' Market", desc: "Monthly market with 60+ local producers", category: "shop" },
      { label: "The Dark Horse", desc: "Beloved local pub with a huge garden", category: "pub" },
    ],
    propertyMix: { D: 12, S: 18, T: 48, F: 20, O: 2 },
    broadband: { download: 188, upload: 38, coverage5g: false },
    crimeIndex: { local: 65, borough: 62, city: 68 },
    agent: { name: "Sarah Millward", role: "Senior Valuer", quote: "Moseley's Victorian terraces have huge kerb appeal — presentation makes all the difference here.", initials: "SM" },
    transportLinks: [
      { name: "Kings Heath Bus Corridor", type: "bus", detail: "Route 50 — 20 min to Birmingham New St", emoji: "🚌" },
      { name: "Birmingham Moor Street", type: "rail", detail: "20 min by bus or taxi", emoji: "🚆" },
    ],
  },

  // Bristol
  "bristol/clifton": {
    slug: "clifton",
    name: "Clifton",
    citySlug: "bristol",
    cityName: "Bristol",
    borough: "Clifton & Hotwells",
    postcode: "BS8",
    description: "Clifton is Bristol's most prestigious neighbourhood, defined by its Georgian crescents, the world-famous suspension bridge and a thriving village of boutiques, restaurants and delis. It attracts affluent families, academics from Bristol University and well-heeled retirees seeking a polished yet vibrant urban village.",
    coordinates: { lat: 51.4568, lng: -2.6239 },
    avgPrice: 550000,
    avgPriceFormatted: "£550,000",
    yoyChange: "+3.4%",
    greenSpace: "30%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Professionals & Academics", medianAge: 40, ownerOccupied: 55, privateRented: 38, socialRented: 7, vibe: "Cultured & affluent" },
    schools: [
      { name: "Clifton High School", ofsted: "Outstanding", distance: "0.3 mi", type: "All-through" },
      { name: "Hope Chapel Primary", ofsted: "Good", distance: "0.5 mi", type: "Primary" },
      { name: "Bristol Cathedral Choir School", ofsted: "Outstanding", distance: "0.9 mi", type: "Secondary" },
    ],
    localFavourites: [
      { label: "Clifton Suspension Bridge", desc: "Brunel's iconic landmark with gorge walks below", category: "attraction" },
      { label: "Clifton Lido", desc: "Grade II-listed Victorian lido with spa and restaurant", category: "attraction" },
      { label: "The Victoria", desc: "Award-winning gastropub on Chleddar Road", category: "pub" },
    ],
    propertyMix: { D: 18, S: 14, T: 22, F: 44, O: 2 },
    broadband: { download: 210, upload: 45, coverage5g: true },
    crimeIndex: { local: 48, borough: 62, city: 65 },
    agent: { name: "James Alford", role: "Director", quote: "Clifton Georgian conversions are the benchmark — buyers come back year after year until they secure one.", initials: "JA" },
    transportLinks: [
      { name: "Clifton Down", type: "rail", detail: "Severn Beach line — 15 min to Bristol Temple Meads", emoji: "🚆" },
      { name: "Clifton Down Bus", type: "bus", detail: "Route 8 — frequent service to centre", emoji: "🚌" },
    ],
  },
  "bristol/redland": {
    slug: "redland",
    name: "Redland",
    citySlug: "bristol",
    cityName: "Bristol",
    borough: "Redland & Cotham",
    postcode: "BS6",
    description: "Redland is a sought-after family neighbourhood bordering Clifton, with wide tree-lined streets of Victorian villas and excellent state schools. The combination of green spaces, independent cafés and easy cycling distance from the university makes it one of Bristol's most competitive markets.",
    coordinates: { lat: 51.4677, lng: -2.6056 },
    avgPrice: 490000,
    avgPriceFormatted: "£490,000",
    yoyChange: "+4.0%",
    greenSpace: "26%",
    walkability: "Medium",
    noiseLevel: "Quiet",
    demographics: { topGroup: "Families", medianAge: 39, ownerOccupied: 58, privateRented: 35, socialRented: 7, vibe: "Established family suburb" },
    schools: [
      { name: "Redland Green School", ofsted: "Outstanding", distance: "0.3 mi", type: "Secondary" },
      { name: "Redland Primary School", ofsted: "Outstanding", distance: "0.4 mi", type: "Primary" },
      { name: "Westbury-on-Trym CE Primary", ofsted: "Good", distance: "0.8 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Redland Park", desc: "Quiet neighbourhood park popular with dog walkers", category: "park" },
      { label: "Bravas", desc: "Spanish tapas restaurant with an outdoor terrace", category: "cafe" },
      { label: "The Lazy Dog", desc: "Cosy pub with a reputation for Sunday roasts", category: "pub" },
    ],
    propertyMix: { D: 20, S: 22, T: 40, F: 16, O: 2 },
    broadband: { download: 195, upload: 40, coverage5g: true },
    crimeIndex: { local: 44, borough: 55, city: 65 },
    agent: { name: "Fiona Blake", role: "Sales Director", quote: "Redland Green catchment adds 10–15% to asking price — families know exactly what they want.", initials: "FB" },
    transportLinks: [
      { name: "Redland Rail", type: "rail", detail: "Severn Beach line — 18 min to Temple Meads", emoji: "🚆" },
      { name: "Whiteladies Road Bus", type: "bus", detail: "Route 9 — frequent to city centre", emoji: "🚌" },
    ],
  },
  "bristol/bedminster": {
    slug: "bedminster",
    name: "Bedminster",
    citySlug: "bristol",
    cityName: "Bristol",
    borough: "Bedminster & Southville",
    postcode: "BS3",
    description: "Bedminster and neighbouring Southville are Bristol's emerging south-side hotspot, where ex-industrial streets are lined with independent traders, coffee roasters and street art under Banksy's famous mural. Strong community spirit, great value and proximity to the centre make it hugely popular with first-time buyers.",
    coordinates: { lat: 51.4411, lng: -2.6020 },
    avgPrice: 340000,
    avgPriceFormatted: "£340,000",
    yoyChange: "+5.6%",
    greenSpace: "18%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "First-time Buyers & Young Couples", medianAge: 33, ownerOccupied: 44, privateRented: 48, socialRented: 8, vibe: "Gritty, creative & community-led" },
    schools: [
      { name: "Bedminster Down School", ofsted: "Good", distance: "0.6 mi", type: "Secondary" },
      { name: "Compass Point Primary", ofsted: "Good", distance: "0.4 mi", type: "Primary" },
      { name: "Ashton Gate Primary School", ofsted: "Good", distance: "0.5 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "North Street", desc: "Independent traders' street with award-winning delis and bars", category: "shop" },
      { label: "Tobacco Factory Theatre", desc: "Multi-purpose arts venue and Sunday market", category: "attraction" },
      { label: "The Hen & Chicken", desc: "Comedy and live music pub venue", category: "pub" },
    ],
    propertyMix: { D: 5, S: 12, T: 55, F: 26, O: 2 },
    broadband: { download: 188, upload: 38, coverage5g: false },
    crimeIndex: { local: 72, borough: 68, city: 65 },
    agent: { name: "Matt Jennings", role: "Sales Manager", quote: "Bedminster is the best value story in Bristol right now — buyers are realising it quickly.", initials: "MJ" },
    transportLinks: [
      { name: "Parson Street Rail", type: "rail", detail: "Severn Beach line — 10 min to Temple Meads", emoji: "🚆" },
      { name: "Bedminster Parade Bus", type: "bus", detail: "Routes 24/25 to city centre", emoji: "🚌" },
    ],
  },
  "bristol/stokes-croft": {
    slug: "stokes-croft",
    name: "Stokes Croft",
    citySlug: "bristol",
    cityName: "Bristol",
    borough: "Lawrence Hill & Easton",
    postcode: "BS1",
    description: "Stokes Croft is Bristol's self-declared 'People's Republic' — a counter-cultural corridor of street art, vegan cafés, independent record shops and grassroots music venues. It polarises opinion but offers some of the cheapest central Bristol property, attracting artists, activists and savvy investors.",
    coordinates: { lat: 51.4610, lng: -2.5958 },
    avgPrice: 295000,
    avgPriceFormatted: "£295,000",
    yoyChange: "+6.2%",
    greenSpace: "8%",
    walkability: "High",
    noiseLevel: "Busy",
    demographics: { topGroup: "Artists & Students", medianAge: 28, ownerOccupied: 20, privateRented: 72, socialRented: 8, vibe: "Counter-cultural & raw" },
    schools: [
      { name: "St Barnabas CE Primary", ofsted: "Good", distance: "0.5 mi", type: "Primary" },
      { name: "City Academy Bristol", ofsted: "Good", distance: "0.6 mi", type: "Secondary" },
      { name: "Bristol Free School", ofsted: "Good", distance: "0.8 mi", type: "All-through" },
    ],
    localFavourites: [
      { label: "Stokes Croft Murals", desc: "UK's highest concentration of legal street art", category: "attraction" },
      { label: "Cafe Kino", desc: "Anarchist co-operative café serving vegan food", category: "cafe" },
      { label: "The Crofters Rights", desc: "No-frills music pub with a dedicated local following", category: "pub" },
    ],
    propertyMix: { D: 1, S: 4, T: 18, F: 74, O: 3 },
    broadband: { download: 200, upload: 42, coverage5g: true },
    crimeIndex: { local: 108, borough: 78, city: 65 },
    agent: { name: "Amy Pearce", role: "Urban Specialist", quote: "Stokes Croft flats yield well and the long-term capital growth story is very compelling.", initials: "AP" },
    transportLinks: [
      { name: "Bristol Temple Meads", type: "rail", detail: "15 min walk to national rail hub", emoji: "🚆" },
      { name: "Stokes Croft Bus", type: "bus", detail: "Routes 72/73 — frequent service", emoji: "🚌" },
    ],
  },

  // Leeds
  "leeds/headingley": {
    slug: "headingley",
    name: "Headingley",
    citySlug: "leeds",
    cityName: "Leeds",
    borough: "Headingley & Hyde Park",
    postcode: "LS6",
    description: "Headingley is Leeds' vibrant student district, home to two universities and the famous cricket ground. Victorian terraces are largely HMOs but the area also attracts young professionals drawn by the independent restaurants on Otley Road, excellent transport links and a lively social scene.",
    coordinates: { lat: 53.8215, lng: -1.5818 },
    avgPrice: 240000,
    avgPriceFormatted: "£240,000",
    yoyChange: "+4.8%",
    greenSpace: "22%",
    walkability: "High",
    noiseLevel: "Busy",
    demographics: { topGroup: "Students & Young Professionals", medianAge: 26, ownerOccupied: 18, privateRented: 76, socialRented: 6, vibe: "Student-dominated & lively" },
    schools: [
      { name: "Headingley CE Primary School", ofsted: "Good", distance: "0.4 mi", type: "Primary" },
      { name: "Lawnswood School", ofsted: "Outstanding", distance: "0.8 mi", type: "Secondary" },
      { name: "St Michael's College", ofsted: "Good", distance: "0.6 mi", type: "Secondary" },
    ],
    localFavourites: [
      { label: "Headingley Stadium", desc: "Home of Yorkshire Cricket and Leeds Rhinos", category: "attraction" },
      { label: "Laynes Espresso", desc: "Pioneer of Leeds' speciality coffee scene", category: "cafe" },
      { label: "The Skyrack", desc: "Traditional pub on the site of a famous ancient oak", category: "pub" },
    ],
    propertyMix: { D: 3, S: 8, T: 58, F: 28, O: 3 },
    broadband: { download: 195, upload: 42, coverage5g: true },
    crimeIndex: { local: 88, borough: 72, city: 66 },
    agent: { name: "Mark Thornton", role: "BTL Director", quote: "HMO yields in Headingley average 8% — one of the strongest BTL postcodes in the north.", initials: "MT" },
    transportLinks: [
      { name: "Headingley Rail", type: "rail", detail: "Wharfedale line — 8 min to Leeds city centre", emoji: "🚆" },
      { name: "Otley Road Bus", type: "bus", detail: "Route 28 — frequent service to Leeds centre", emoji: "🚌" },
    ],
  },
  "leeds/roundhay": {
    slug: "roundhay",
    name: "Roundhay",
    citySlug: "leeds",
    cityName: "Leeds",
    borough: "Roundhay & Moortown",
    postcode: "LS8",
    description: "Roundhay is Leeds' premier family suburb, anchored by one of Europe's largest urban parks. Detached Edwardian and 1930s properties on wide, tree-lined streets attract senior professionals and affluent families. The park, lake and excellent schools make it consistently one of Yorkshire's most desired addresses.",
    coordinates: { lat: 53.8358, lng: -1.5205 },
    avgPrice: 430000,
    avgPriceFormatted: "£430,000",
    yoyChange: "+3.2%",
    greenSpace: "44%",
    walkability: "Medium",
    noiseLevel: "Quiet",
    demographics: { topGroup: "Affluent Families", medianAge: 45, ownerOccupied: 70, privateRented: 24, socialRented: 6, vibe: "Established & family-focused" },
    schools: [
      { name: "Roundhay School", ofsted: "Outstanding", distance: "0.5 mi", type: "Secondary" },
      { name: "Gledhow Primary School", ofsted: "Good", distance: "0.4 mi", type: "Primary" },
      { name: "Roundhay St John's CE Primary", ofsted: "Outstanding", distance: "0.3 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Roundhay Park", desc: "700-acre park with two lakes and a tropical world", category: "park" },
      { label: "Oakwood Clock", desc: "Popular café and deli hub around the landmark clock", category: "cafe" },
      { label: "The Roundhay Fox", desc: "Smart gastropub with seasonal Sunday menus", category: "pub" },
    ],
    propertyMix: { D: 42, S: 28, T: 18, F: 10, O: 2 },
    broadband: { download: 188, upload: 38, coverage5g: true },
    crimeIndex: { local: 32, borough: 48, city: 66 },
    agent: { name: "Victoria Hargreaves", role: "Partner", quote: "Roundhay detacheds are generational holds — we see the same families returning decade after decade.", initials: "VH" },
    transportLinks: [
      { name: "Roundhay Bus", type: "bus", detail: "Routes 2/12 — 20 min to Leeds centre", emoji: "🚌" },
      { name: "Cross Gates Rail", type: "rail", detail: "15 min by car/bus to Leeds city centre", emoji: "🚆" },
    ],
  },
  "leeds/chapel-allerton": {
    slug: "chapel-allerton",
    name: "Chapel Allerton",
    citySlug: "leeds",
    cityName: "Leeds",
    borough: "Chapel Allerton",
    postcode: "LS7",
    description: "Chapel Allerton is Leeds' most fashionable neighbourhood, with a packed high street of independent restaurants, bars and boutiques that punches well above the postcode's weight. Popular with young professionals and growing families, it combines urban energy with quality Victorian housing stock.",
    coordinates: { lat: 53.8290, lng: -1.5436 },
    avgPrice: 320000,
    avgPriceFormatted: "£320,000",
    yoyChange: "+5.4%",
    greenSpace: "20%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Young Professionals & Families", medianAge: 35, ownerOccupied: 50, privateRented: 42, socialRented: 8, vibe: "Trendy & community-oriented" },
    schools: [
      { name: "Carr Manor Community School", ofsted: "Good", distance: "0.6 mi", type: "Secondary" },
      { name: "Chapel Allerton Primary School", ofsted: "Good", distance: "0.3 mi", type: "Primary" },
      { name: "Allerton CE Primary School", ofsted: "Outstanding", distance: "0.5 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Potternewton Park", desc: "Popular local park with a café and tennis courts", category: "park" },
      { label: "Bundobust", desc: "Indian street food and craft beer institution", category: "cafe" },
      { label: "The Mustard Pot", desc: "Classic neighbourhood pub with a good food menu", category: "pub" },
    ],
    propertyMix: { D: 14, S: 20, T: 48, F: 16, O: 2 },
    broadband: { download: 200, upload: 44, coverage5g: true },
    crimeIndex: { local: 60, borough: 65, city: 66 },
    agent: { name: "Sophie Whitaker", role: "Sales Manager", quote: "Chapel Allerton is Leeds' most competitive postcode right now — houses sell in days.", initials: "SW" },
    transportLinks: [
      { name: "Harehills Lane Bus", type: "bus", detail: "Routes 2/3 — 15 min to Leeds city centre", emoji: "🚌" },
      { name: "Leeds Rail", type: "rail", detail: "Short bus/taxi ride to main rail hub", emoji: "🚆" },
    ],
  },
  "leeds/kirkstall": {
    slug: "kirkstall",
    name: "Kirkstall",
    citySlug: "leeds",
    cityName: "Leeds",
    borough: "Kirkstall & Bramley",
    postcode: "LS5",
    description: "Kirkstall is a characterful riverside neighbourhood anchored by one of England's best-preserved ruined abbeys. Affordable Victorian terraces, improving schools and good transport links have made it a first port of call for buyers priced out of Headingley and Chapel Allerton.",
    coordinates: { lat: 53.8143, lng: -1.6098 },
    avgPrice: 255000,
    avgPriceFormatted: "£255,000",
    yoyChange: "+5.0%",
    greenSpace: "28%",
    walkability: "Medium",
    noiseLevel: "Moderate",
    demographics: { topGroup: "First-time Buyers & Young Families", medianAge: 33, ownerOccupied: 46, privateRented: 46, socialRented: 8, vibe: "Affordable & up-and-coming" },
    schools: [
      { name: "Kirkstall Valley Primary", ofsted: "Good", distance: "0.4 mi", type: "Primary" },
      { name: "Abbey Grange CE Academy", ofsted: "Good", distance: "0.6 mi", type: "Secondary" },
      { name: "Bramley St Peter's CE Primary", ofsted: "Good", distance: "0.8 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Kirkstall Abbey", desc: "12th-century Cistercian ruins set in riverside grounds", category: "attraction" },
      { label: "Aire Valley Towpath", desc: "Scenic cycling and walking route along the river", category: "park" },
      { label: "The Abbey Inn", desc: "Pub directly facing the ruins — hard to beat for atmosphere", category: "pub" },
    ],
    propertyMix: { D: 8, S: 15, T: 58, F: 17, O: 2 },
    broadband: { download: 185, upload: 36, coverage5g: false },
    crimeIndex: { local: 65, borough: 68, city: 66 },
    agent: { name: "Gary Sykes", role: "Valuer", quote: "Kirkstall is the honest choice for buyers who want character and a garden without the Headingley premium.", initials: "GS" },
    transportLinks: [
      { name: "Kirkstall Forge Rail", type: "rail", detail: "Wharfedale line — 12 min to Leeds station", emoji: "🚆" },
      { name: "Kirkstall Road Bus", type: "bus", detail: "Route 33/33A — frequent to city centre", emoji: "🚌" },
    ],
  },

  // Edinburgh
  "edinburgh/leith": {
    slug: "leith",
    name: "Leith",
    citySlug: "edinburgh",
    cityName: "Edinburgh",
    borough: "Leith",
    postcode: "EH6",
    description: "Leith is Edinburgh's former port district, now transformed into one of Scotland's most exciting neighbourhoods. The Shore waterfront bristles with Michelin-starred restaurants, craft bars and gallery spaces, while affordable Georgian flats continue to attract first-time buyers and investors alike.",
    coordinates: { lat: 55.9736, lng: -3.1730 },
    avgPrice: 295000,
    avgPriceFormatted: "£295,000",
    yoyChange: "+6.0%",
    greenSpace: "15%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Young Professionals & Creatives", medianAge: 32, ownerOccupied: 38, privateRented: 52, socialRented: 10, vibe: "Maritime cool & regenerating" },
    schools: [
      { name: "Leith Academy", ofsted: "Good", distance: "0.5 mi", type: "Secondary" },
      { name: "St Mary's RC Primary School Leith", ofsted: "Good", distance: "0.4 mi", type: "Primary" },
      { name: "Lorne Primary School", ofsted: "Outstanding", distance: "0.6 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "The Shore", desc: "Award-winning waterfront strip with Scotland's finest restaurants", category: "attraction" },
      { label: "Royal Yacht Britannia", desc: "HMY Britannia, now a visitor attraction and event venue", category: "attraction" },
      { label: "The Roseleaf Bar", desc: "Eclectic bar serving cocktails in teapots", category: "pub" },
    ],
    propertyMix: { D: 4, S: 8, T: 15, F: 70, O: 3 },
    broadband: { download: 220, upload: 50, coverage5g: true },
    crimeIndex: { local: 78, borough: 82, city: 70 },
    agent: { name: "Catriona MacDonald", role: "Area Specialist", quote: "Leith's trajectory mirrors Shoreditch — buyers ten years ago are sitting on life-changing gains.", initials: "CM" },
    transportLinks: [
      { name: "Newhaven Tram", type: "tram", detail: "Edinburgh Trams — 25 min to city centre", emoji: "🚊" },
      { name: "Ocean Terminal Bus", type: "bus", detail: "Routes 16/22 — frequent to Princes Street", emoji: "🚌" },
    ],
  },
  "edinburgh/stockbridge": {
    slug: "stockbridge",
    name: "Stockbridge",
    citySlug: "edinburgh",
    cityName: "Edinburgh",
    borough: "Inverleith & Stockbridge",
    postcode: "EH3",
    description: "Stockbridge is Edinburgh's most coveted village neighbourhood, nestled in a Water of Leith gorge with Georgian crescents, a beloved Sunday market and an independent high street. It attracts young professional families who prize the Botanics, outstanding schools and a genuine village community inside the city.",
    coordinates: { lat: 55.9577, lng: -3.2109 },
    avgPrice: 520000,
    avgPriceFormatted: "£520,000",
    yoyChange: "+3.8%",
    greenSpace: "32%",
    walkability: "High",
    noiseLevel: "Quiet",
    demographics: { topGroup: "Professional Families", medianAge: 40, ownerOccupied: 60, privateRented: 35, socialRented: 5, vibe: "Village chic" },
    schools: [
      { name: "Stockbridge Primary School", ofsted: "Outstanding", distance: "0.3 mi", type: "Primary" },
      { name: "The Royal High School Edinburgh", ofsted: "Outstanding", distance: "0.7 mi", type: "Secondary" },
      { name: "Broughton High School", ofsted: "Good", distance: "0.6 mi", type: "Secondary" },
    ],
    localFavourites: [
      { label: "Royal Botanic Garden", desc: "72-acre garden with glasshouses and a sculpture trail", category: "park" },
      { label: "Stockbridge Market", desc: "Sunday artisan market on Saunders Street", category: "shop" },
      { label: "The Baillie Bar", desc: "Quintessential Edinburgh local in a Georgian basement", category: "pub" },
    ],
    propertyMix: { D: 10, S: 12, T: 18, F: 58, O: 2 },
    broadband: { download: 210, upload: 46, coverage5g: true },
    crimeIndex: { local: 45, borough: 55, city: 70 },
    agent: { name: "Hamish Fraser", role: "Senior Partner", quote: "Stockbridge flats don't come up often — when they do, they're gone before the weekend.", initials: "HF" },
    transportLinks: [
      { name: "Princes Street Bus", type: "bus", detail: "Routes 23/27 — 10 min to city centre", emoji: "🚌" },
      { name: "Edinburgh Waverley", type: "rail", detail: "25 min walk or short bus to main rail hub", emoji: "🚆" },
    ],
  },
  "edinburgh/morningside": {
    slug: "morningside",
    name: "Morningside",
    citySlug: "edinburgh",
    cityName: "Edinburgh",
    borough: "Morningside & Bruntsfield",
    postcode: "EH10",
    description: "Morningside is Edinburgh's benchmark of middle-class respectability — a neighbourhood of stone-built Victorian villas, excellent independent schools and a high street of butchers, delis and bookshops. It consistently scores highest in quality-of-life surveys and is the top choice for established Edinburgh families.",
    coordinates: { lat: 55.9276, lng: -3.2054 },
    avgPrice: 560000,
    avgPriceFormatted: "£560,000",
    yoyChange: "+3.0%",
    greenSpace: "35%",
    walkability: "Medium",
    noiseLevel: "Quiet",
    demographics: { topGroup: "Established Families", medianAge: 46, ownerOccupied: 68, privateRented: 26, socialRented: 6, vibe: "Conservative & refined" },
    schools: [
      { name: "South Morningside Primary School", ofsted: "Outstanding", distance: "0.3 mi", type: "Primary" },
      { name: "Boroughmuir High School", ofsted: "Outstanding", distance: "0.4 mi", type: "Secondary" },
      { name: "George Watson's College", ofsted: "Outstanding", distance: "0.5 mi", type: "All-through" },
    ],
    localFavourites: [
      { label: "Hermitage of Braid", desc: "Local nature reserve with a babbling burn and ancient oaks", category: "park" },
      { label: "Bibi's Cantina", desc: "Popular neighbourhood bistro on Morningside Road", category: "cafe" },
      { label: "The Canny Man's", desc: "Legendarily eccentric Edinburgh institution", category: "pub" },
    ],
    propertyMix: { D: 30, S: 25, T: 20, F: 23, O: 2 },
    broadband: { download: 200, upload: 42, coverage5g: true },
    crimeIndex: { local: 35, borough: 48, city: 70 },
    agent: { name: "Fiona Stewart", role: "Director", quote: "Morningside buyers are rarely in a hurry — but when the right property comes up, they move decisively.", initials: "FS" },
    transportLinks: [
      { name: "Morningside Road Bus", type: "bus", detail: "Routes 5/23/36 — 20 min to Princes Street", emoji: "🚌" },
      { name: "Bruntsfield Bus", type: "bus", detail: "Routes 11/15 — city-wide connectivity", emoji: "🚌" },
    ],
  },
  "edinburgh/new-town": {
    slug: "new-town",
    name: "New Town",
    citySlug: "edinburgh",
    cityName: "Edinburgh",
    borough: "City Centre & New Town",
    postcode: "EH2",
    description: "Edinburgh's New Town is a UNESCO World Heritage masterpiece of Georgian town planning, with wide Georgian streets, elegant squares and some of the finest architecture in Europe. It is Edinburgh's most expensive and prestigious address, popular with financiers, lawyers and international buyers.",
    coordinates: { lat: 55.9560, lng: -3.2021 },
    avgPrice: 680000,
    avgPriceFormatted: "£680,000",
    yoyChange: "+2.8%",
    greenSpace: "18%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Wealthy Professionals", medianAge: 42, ownerOccupied: 50, privateRented: 44, socialRented: 6, vibe: "Grand & cosmopolitan" },
    schools: [
      { name: "Flora Stevenson Primary School", ofsted: "Outstanding", distance: "0.4 mi", type: "Primary" },
      { name: "Broughton High School", ofsted: "Good", distance: "0.5 mi", type: "Secondary" },
      { name: "Edinburgh Academy", ofsted: "Outstanding", distance: "0.6 mi", type: "All-through" },
    ],
    localFavourites: [
      { label: "Princes Street Gardens", desc: "Iconic gardens with castle views and the Scott Monument", category: "park" },
      { label: "Valvona & Crolla", desc: "Italy's finest deli as transplanted to Elm Row since 1934", category: "shop" },
      { label: "The Oxford Bar", desc: "Unassuming pub made famous as Inspector Rebus's local", category: "pub" },
    ],
    propertyMix: { D: 5, S: 8, T: 12, F: 73, O: 2 },
    broadband: { download: 240, upload: 55, coverage5g: true },
    crimeIndex: { local: 90, borough: 80, city: 70 },
    agent: { name: "Alasdair Grant", role: "Head of Residential", quote: "New Town Georgian flats are finite stock in a World Heritage Site — they only appreciate.", initials: "AG" },
    transportLinks: [
      { name: "Edinburgh Waverley", type: "rail", detail: "10 min walk — national and international rail", emoji: "🚆" },
      { name: "Princes Street Tram", type: "tram", detail: "Edinburgh Trams — direct to airport", emoji: "🚊" },
    ],
  },

  // Oxford
  "oxford/jericho": {
    slug: "jericho",
    name: "Jericho",
    citySlug: "oxford",
    cityName: "Oxford",
    borough: "North Oxford",
    postcode: "OX2",
    description: "Jericho is Oxford's most desirable neighbourhood — a Victorian working-class quarter reinvented as a cultural hub with the Oxfam HQ, Phoenix Cinema, independent bookshops and excellent restaurants. Streets of two-up-two-down terraces command premium prices due to their proximity to the university and the centre.",
    coordinates: { lat: 51.7584, lng: -1.2681 },
    avgPrice: 580000,
    avgPriceFormatted: "£580,000",
    yoyChange: "+3.5%",
    greenSpace: "20%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Academics & Professionals", medianAge: 38, ownerOccupied: 48, privateRented: 44, socialRented: 8, vibe: "Academic & cultured" },
    schools: [
      { name: "St Barnabas CE Primary", ofsted: "Good", distance: "0.2 mi", type: "Primary" },
      { name: "Oxford Tutorial College", ofsted: "Outstanding", distance: "0.5 mi", type: "Secondary" },
      { name: "Cherwell School", ofsted: "Good", distance: "0.7 mi", type: "Secondary" },
    ],
    localFavourites: [
      { label: "Port Meadow", desc: "Ancient common land for walking and wild swimming", category: "park" },
      { label: "The Jericho Café", desc: "Neighbourhood café beloved by academics", category: "cafe" },
      { label: "The Lamb & Flag", desc: "15th-century pub that funded CS Lewis's Inklings meetings", category: "pub" },
    ],
    propertyMix: { D: 8, S: 12, T: 48, F: 30, O: 2 },
    broadband: { download: 210, upload: 46, coverage5g: true },
    crimeIndex: { local: 55, borough: 60, city: 58 },
    agent: { name: "Oliver Chambers", role: "Director", quote: "Jericho terraces hold value through every cycle — academic demand is virtually recession-proof.", initials: "OC" },
    transportLinks: [
      { name: "Oxford Rail", type: "rail", detail: "15 min walk to Oxford station — London in 55 min", emoji: "🚆" },
      { name: "Walton Street Bus", type: "bus", detail: "Routes 2/7 — Oxford city buses", emoji: "🚌" },
    ],
  },
  "oxford/summertown": {
    slug: "summertown",
    name: "Summertown",
    citySlug: "oxford",
    cityName: "Oxford",
    borough: "North Oxford",
    postcode: "OX2",
    description: "Summertown is Oxford's premium family suburb, with a strong independent high street, excellent state and private schools and wide streets of substantial Edwardian and inter-war homes. It is the first choice for Oxford dons with families and professional households wanting space within the city.",
    coordinates: { lat: 51.7755, lng: -1.2647 },
    avgPrice: 680000,
    avgPriceFormatted: "£680,000",
    yoyChange: "+2.9%",
    greenSpace: "28%",
    walkability: "Medium",
    noiseLevel: "Quiet",
    demographics: { topGroup: "Professional Families & Academics", medianAge: 44, ownerOccupied: 62, privateRented: 30, socialRented: 8, vibe: "Leafy & intellectual" },
    schools: [
      { name: "Cutteslowe Primary School", ofsted: "Good", distance: "0.4 mi", type: "Primary" },
      { name: "Oxford High School GDST", ofsted: "Outstanding", distance: "0.3 mi", type: "Secondary" },
      { name: "Dragon School", ofsted: "Outstanding", distance: "0.5 mi", type: "All-through" },
    ],
    localFavourites: [
      { label: "South Park", desc: "Hilltop park with panoramic views over the dreaming spires", category: "park" },
      { label: "Wych Elm Organic Deli", desc: "North Oxford institution for artisan produce", category: "shop" },
      { label: "The Victoria", desc: "Proper neighbourhood pub with a good wine list", category: "pub" },
    ],
    propertyMix: { D: 30, S: 28, T: 22, F: 18, O: 2 },
    broadband: { download: 200, upload: 42, coverage5g: true },
    crimeIndex: { local: 38, borough: 50, city: 58 },
    agent: { name: "Charlotte Webb", role: "Senior Partner", quote: "Summertown detacheds are the ultimate Oxford family home — demand has never wavered.", initials: "CW" },
    transportLinks: [
      { name: "Banbury Road Bus", type: "bus", detail: "Routes S2/S3 — 15 min to Oxford centre", emoji: "🚌" },
      { name: "Oxford Rail", type: "rail", detail: "20 min by bus/bike to Oxford station", emoji: "🚆" },
    ],
  },
  "oxford/cowley": {
    slug: "cowley",
    name: "Cowley",
    citySlug: "oxford",
    cityName: "Oxford",
    borough: "Cowley & Littlemore",
    postcode: "OX4",
    description: "Cowley is Oxford's most affordable and diverse inner suburb, with a high street of independent shops, a thriving music scene centred on the O2 Academy and a large student and young professional population. Its terraced streets offer remarkable value for an Oxford postcode.",
    coordinates: { lat: 51.7396, lng: -1.2230 },
    avgPrice: 380000,
    avgPriceFormatted: "£380,000",
    yoyChange: "+5.2%",
    greenSpace: "16%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Students, Graduates & Diverse Communities", medianAge: 30, ownerOccupied: 35, privateRented: 55, socialRented: 10, vibe: "Diverse & affordable" },
    schools: [
      { name: "Donnington Primary School", ofsted: "Good", distance: "0.4 mi", type: "Primary" },
      { name: "Cheney School", ofsted: "Good", distance: "0.5 mi", type: "Secondary" },
      { name: "St Christopher's CE Middle School", ofsted: "Good", distance: "0.6 mi", type: "Secondary" },
    ],
    localFavourites: [
      { label: "East Oxford Farmers' Market", desc: "Saturday market on Gloucester Green", category: "shop" },
      { label: "The Truck Store", desc: "Independent record shop and live music venue", category: "attraction" },
      { label: "The James Street Tavern", desc: "Welcoming local with an excellent beer selection", category: "pub" },
    ],
    propertyMix: { D: 5, S: 10, T: 55, F: 28, O: 2 },
    broadband: { download: 195, upload: 40, coverage5g: false },
    crimeIndex: { local: 80, borough: 70, city: 58 },
    agent: { name: "Ben Harvey", role: "Sales Negotiator", quote: "Cowley is Oxford's best-kept secret for first-time buyers — they're catching on fast.", initials: "BH" },
    transportLinks: [
      { name: "Cowley Road Bus", type: "bus", detail: "Routes 1/5 — 15 min to Oxford city centre", emoji: "🚌" },
      { name: "Oxford Rail", type: "rail", detail: "20 min cycle via Cycleway 5 to Oxford station", emoji: "🚆" },
    ],
  },

  // Cambridge
  "cambridge/newnham": {
    slug: "newnham",
    name: "Newnham",
    citySlug: "cambridge",
    cityName: "Cambridge",
    borough: "Newnham",
    postcode: "CB3",
    description: "Newnham is Cambridge's most sought-after residential neighbourhood — a village of handsome Victorian and Edwardian houses with large gardens backing onto the Cam. Home to Newnham College, the area combines academic prestige with peaceful residential streets and beautiful riverside walks.",
    coordinates: { lat: 52.1980, lng: 0.1028 },
    avgPrice: 650000,
    avgPriceFormatted: "£650,000",
    yoyChange: "+3.2%",
    greenSpace: "38%",
    walkability: "High",
    noiseLevel: "Quiet",
    demographics: { topGroup: "Academics & Senior Professionals", medianAge: 46, ownerOccupied: 60, privateRented: 34, socialRented: 6, vibe: "Quietly distinguished" },
    schools: [
      { name: "Newnham Croft Primary School", ofsted: "Outstanding", distance: "0.3 mi", type: "Primary" },
      { name: "Hills Road Sixth Form College", ofsted: "Outstanding", distance: "0.8 mi", type: "Secondary" },
      { name: "The Perse School", ofsted: "Outstanding", distance: "0.6 mi", type: "All-through" },
    ],
    localFavourites: [
      { label: "Grantchester Meadows", desc: "Famous riverside walk to the Rupert Brooke pub", category: "park" },
      { label: "Hot Numbers Coffee", desc: "Specialist coffee roaster with a devoted following", category: "cafe" },
      { label: "The Granta", desc: "Idyllic riverside pub with punts moored outside", category: "pub" },
    ],
    propertyMix: { D: 32, S: 26, T: 24, F: 16, O: 2 },
    broadband: { download: 210, upload: 46, coverage5g: true },
    crimeIndex: { local: 32, borough: 45, city: 52 },
    agent: { name: "Emily Hartley", role: "Director", quote: "Newnham properties rarely come to open market — most sell through our database of waiting buyers.", initials: "EH" },
    transportLinks: [
      { name: "Cambridge Rail", type: "rail", detail: "15 min cycle to Cambridge station — King's Cross 50 min", emoji: "🚆" },
      { name: "Barton Road Bus", type: "bus", detail: "Route Citi 4 — city-wide service", emoji: "🚌" },
    ],
  },
  "cambridge/chesterton": {
    slug: "chesterton",
    name: "Chesterton",
    citySlug: "cambridge",
    cityName: "Cambridge",
    borough: "Chesterton & King's Hedges",
    postcode: "CB4",
    description: "Chesterton is Cambridge's most affordable inner suburb, a riverside neighbourhood on the north bank of the Cam with improving schools, a weekly market and Victorian terraces well within reach of first-time buyers. The Elizabeth line extension has fuelled fresh investor and owner-occupier interest.",
    coordinates: { lat: 52.2218, lng: 0.1280 },
    avgPrice: 450000,
    avgPriceFormatted: "£450,000",
    yoyChange: "+5.0%",
    greenSpace: "22%",
    walkability: "Medium",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Young Families & First-time Buyers", medianAge: 34, ownerOccupied: 50, privateRented: 42, socialRented: 8, vibe: "Unpretentious & neighbourly" },
    schools: [
      { name: "St Luke's CE Primary School", ofsted: "Good", distance: "0.4 mi", type: "Primary" },
      { name: "Chesterton Community College", ofsted: "Good", distance: "0.5 mi", type: "Secondary" },
      { name: "Milton Road Primary School", ofsted: "Outstanding", distance: "0.6 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Stourbridge Common", desc: "Open riverside common popular with families and cyclists", category: "park" },
      { label: "Chesterton Kitchen", desc: "Community-focused neighbourhood café and cookery school", category: "cafe" },
      { label: "The Fort St George", desc: "Historic riverside pub with a sun-trap garden", category: "pub" },
    ],
    propertyMix: { D: 14, S: 20, T: 45, F: 19, O: 2 },
    broadband: { download: 195, upload: 40, coverage5g: false },
    crimeIndex: { local: 60, borough: 55, city: 52 },
    agent: { name: "Paul Gregory", role: "Sales Manager", quote: "Chesterton is the entry point to Cambridge ownership — and a very solid long-term investment.", initials: "PG" },
    transportLinks: [
      { name: "Cambridge North Rail", type: "rail", detail: "Cambridge North station — direct to King's Cross", emoji: "🚆" },
      { name: "Mitcham's Corner Bus", type: "bus", detail: "Routes Citi 2/8 — frequent to city centre", emoji: "🚌" },
    ],
  },
  "cambridge/romsey": {
    slug: "romsey",
    name: "Romsey",
    citySlug: "cambridge",
    cityName: "Cambridge",
    borough: "Abbey & Romsey",
    postcode: "CB1",
    description: "Romsey is a dense inner-city neighbourhood to the south-east of the city centre, popular with Cambridge students, young professionals and a diverse local community. Victorian terraces at relatively accessible prices and walking distance from the station make it a favourite first purchase for Cambridge movers.",
    coordinates: { lat: 52.1996, lng: 0.1411 },
    avgPrice: 480000,
    avgPriceFormatted: "£480,000",
    yoyChange: "+4.5%",
    greenSpace: "14%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Students & Young Professionals", medianAge: 30, ownerOccupied: 40, privateRented: 52, socialRented: 8, vibe: "Diverse & youthful" },
    schools: [
      { name: "Morley Memorial Primary School", ofsted: "Outstanding", distance: "0.3 mi", type: "Primary" },
      { name: "Parkside Community College", ofsted: "Good", distance: "0.4 mi", type: "Secondary" },
      { name: "St Bede's Inter-Church School", ofsted: "Good", distance: "0.6 mi", type: "All-through" },
    ],
    localFavourites: [
      { label: "Cherry Hinton Brook Reserve", desc: "Nature reserve with chalk grassland and a chalk pit", category: "park" },
      { label: "Romsey Mill Café", desc: "Community-run café attached to a youth charity", category: "cafe" },
      { label: "The Empress", desc: "Traditional corner pub with real ales and a pool table", category: "pub" },
    ],
    propertyMix: { D: 5, S: 10, T: 55, F: 28, O: 2 },
    broadband: { download: 200, upload: 44, coverage5g: true },
    crimeIndex: { local: 68, borough: 60, city: 52 },
    agent: { name: "Alice Cooper", role: "Residential Consultant", quote: "Romsey gives you walkable Cambridge at a meaningful discount to the west side — smart money knows it.", initials: "AC" },
    transportLinks: [
      { name: "Cambridge Rail", type: "rail", detail: "10 min walk to Cambridge station — King's Cross 50 min", emoji: "🚆" },
      { name: "Mill Road Bus", type: "bus", detail: "Routes Citi 1/3 — frequent city service", emoji: "🚌" },
    ],
  },

  // Liverpool
  "liverpool/baltic-triangle": {
    slug: "baltic-triangle",
    name: "Baltic Triangle",
    citySlug: "liverpool",
    cityName: "Liverpool",
    borough: "Liverpool City Centre",
    postcode: "L1",
    description: "The Baltic Triangle is Liverpool's creative quarter — a former industrial district now packed with digital agencies, independent cinemas, street food markets and the city's best nightlife. Rapid regeneration and new-build apartment developments have drawn a young professional and investor wave.",
    coordinates: { lat: 53.3963, lng: -2.9809 },
    avgPrice: 195000,
    avgPriceFormatted: "£195,000",
    yoyChange: "+7.8%",
    greenSpace: "8%",
    walkability: "High",
    noiseLevel: "Busy",
    demographics: { topGroup: "Young Professionals & Creatives", medianAge: 28, ownerOccupied: 18, privateRented: 78, socialRented: 4, vibe: "Creative & regenerating" },
    schools: [
      { name: "St Patrick's RC Primary Liverpool", ofsted: "Good", distance: "0.6 mi", type: "Primary" },
      { name: "Collegiate Academy", ofsted: "Good", distance: "0.8 mi", type: "Secondary" },
      { name: "Liverpool School of Art and Design", ofsted: "Good", distance: "0.5 mi", type: "All-through" },
    ],
    localFavourites: [
      { label: "Camp and Furnace", desc: "Industrial events space with a year-round food market", category: "attraction" },
      { label: "Baltic Market", desc: "Liverpool's premier street food hall", category: "cafe" },
      { label: "Constellations", desc: "Outdoor bar with live music and a shipping container garden", category: "pub" },
    ],
    propertyMix: { D: 0, S: 1, T: 5, F: 92, O: 2 },
    broadband: { download: 250, upload: 58, coverage5g: true },
    crimeIndex: { local: 105, borough: 90, city: 78 },
    agent: { name: "Connor Hughes", role: "City Specialist", quote: "Baltic Triangle new-builds are outperforming every other Liverpool postcode on gross yield.", initials: "CH" },
    transportLinks: [
      { name: "Liverpool Central", type: "rail", detail: "Merseyrail — 5 min to Central station", emoji: "🚆" },
      { name: "James Street", type: "rail", detail: "Merseyrail — 3 stops to Lime Street", emoji: "🚆" },
    ],
  },
  "liverpool/aigburth": {
    slug: "aigburth",
    name: "Aigburth",
    citySlug: "liverpool",
    cityName: "Liverpool",
    borough: "Aigburth & Garston",
    postcode: "L17",
    description: "Aigburth is one of Liverpool's most desirable family suburbs, with Sefton Park at its heart and wide streets of Victorian villas and Edwardian semis. It attracts professional families seeking access to top schools, green space and the city centre without paying inner-city prices.",
    coordinates: { lat: 53.3716, lng: -2.9407 },
    avgPrice: 320000,
    avgPriceFormatted: "£320,000",
    yoyChange: "+4.2%",
    greenSpace: "36%",
    walkability: "Medium",
    noiseLevel: "Quiet",
    demographics: { topGroup: "Families & Professionals", medianAge: 40, ownerOccupied: 60, privateRented: 32, socialRented: 8, vibe: "Green & aspirational" },
    schools: [
      { name: "St Michael in the Hamlet Primary", ofsted: "Outstanding", distance: "0.3 mi", type: "Primary" },
      { name: "Belvedere Academy", ofsted: "Outstanding", distance: "0.5 mi", type: "Secondary" },
      { name: "Liverpool College", ofsted: "Outstanding", distance: "0.7 mi", type: "All-through" },
    ],
    localFavourites: [
      { label: "Sefton Park", desc: "235-acre Victorian park with a palm house and boating lake", category: "park" },
      { label: "Leaf Tea Shop", desc: "Bohemian tea shop and live music venue", category: "cafe" },
      { label: "The Lark Lane Social", desc: "Lark Lane's most loved neighbourhood bar", category: "pub" },
    ],
    propertyMix: { D: 20, S: 30, T: 28, F: 20, O: 2 },
    broadband: { download: 195, upload: 40, coverage5g: true },
    crimeIndex: { local: 45, borough: 62, city: 78 },
    agent: { name: "Natalie Wood", role: "Residential Partner", quote: "Sefton Park frontages are the crown jewels of Liverpool property — an unmissable address.", initials: "NW" },
    transportLinks: [
      { name: "St Michael's Merseyrail", type: "rail", detail: "City Line — 15 min to Liverpool Central", emoji: "🚆" },
      { name: "Aigburth Bus", type: "bus", detail: "Routes 80/82 — frequent to city centre", emoji: "🚌" },
    ],
  },
  "liverpool/woolton": {
    slug: "woolton",
    name: "Woolton",
    citySlug: "liverpool",
    cityName: "Liverpool",
    borough: "Woolton & Childwall",
    postcode: "L25",
    description: "Woolton is a well-heeled village suburb on Liverpool's south-eastern edge, famous as the birthplace village of John Lennon and Paul McCartney's meeting place. Large detached homes on private roads sit alongside a charming village centre with independent shops and pubs.",
    coordinates: { lat: 53.3711, lng: -2.8770 },
    avgPrice: 380000,
    avgPriceFormatted: "£380,000",
    yoyChange: "+3.5%",
    greenSpace: "40%",
    walkability: "Low",
    noiseLevel: "Quiet",
    demographics: { topGroup: "Established Families", medianAge: 48, ownerOccupied: 72, privateRented: 22, socialRented: 6, vibe: "Village affluence" },
    schools: [
      { name: "St Julie's Catholic High School", ofsted: "Outstanding", distance: "0.4 mi", type: "Secondary" },
      { name: "Woolton Primary School", ofsted: "Good", distance: "0.3 mi", type: "Primary" },
      { name: "Gateacre School", ofsted: "Good", distance: "0.6 mi", type: "Secondary" },
    ],
    localFavourites: [
      { label: "Woolton Woods", desc: "Ancient woodland with bluebells and walking trails", category: "park" },
      { label: "The Elephant", desc: "Upscale village pub and restaurant", category: "pub" },
      { label: "Strawberry Field", desc: "Salvation Army grounds that inspired the Beatles song", category: "attraction" },
    ],
    propertyMix: { D: 45, S: 28, T: 16, F: 9, O: 2 },
    broadband: { download: 175, upload: 32, coverage5g: false },
    crimeIndex: { local: 28, borough: 48, city: 78 },
    agent: { name: "David Mercer", role: "Director", quote: "Woolton detacheds on private roads are the most defensive investment in Merseyside property.", initials: "DM" },
    transportLinks: [
      { name: "Hunts Cross Merseyrail", type: "rail", detail: "City and Northern lines — 25 min to Central", emoji: "🚆" },
      { name: "Woolton Bus", type: "bus", detail: "Routes 75/76 — city bus service", emoji: "🚌" },
    ],
  },

  // Glasgow
  "glasgow/west-end": {
    slug: "west-end",
    name: "West End",
    citySlug: "glasgow",
    cityName: "Glasgow",
    borough: "Hillhead & Partick",
    postcode: "G12",
    description: "Glasgow's West End is the city's most desirable address, centred on the Gothic towers of the University and the Victorian splendour of Byres Road. Cafés, galleries, Kelvingrove Park and a bohemian mix of students and professionals create an environment of rare urban quality.",
    coordinates: { lat: 55.8714, lng: -4.2890 },
    avgPrice: 330000,
    avgPriceFormatted: "£330,000",
    yoyChange: "+4.8%",
    greenSpace: "30%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Academics & Professionals", medianAge: 34, ownerOccupied: 40, privateRented: 52, socialRented: 8, vibe: "Cosmopolitan & cultured" },
    schools: [
      { name: "Hillhead Primary School", ofsted: "Outstanding", distance: "0.3 mi", type: "Primary" },
      { name: "Cleveden Secondary School", ofsted: "Good", distance: "0.5 mi", type: "Secondary" },
      { name: "Notre Dame High School Glasgow", ofsted: "Good", distance: "0.6 mi", type: "Secondary" },
    ],
    localFavourites: [
      { label: "Kelvingrove Park", desc: "85-acre Victorian park with a bandstand and bowling green", category: "park" },
      { label: "Kelvingrove Art Gallery", desc: "Scotland's most visited gallery — free entry always", category: "attraction" },
      { label: "Ubiquitous Chip", desc: "Glasgow dining institution on Ashton Lane since 1971", category: "pub" },
    ],
    propertyMix: { D: 5, S: 8, T: 12, F: 73, O: 2 },
    broadband: { download: 215, upload: 48, coverage5g: true },
    crimeIndex: { local: 68, borough: 74, city: 80 },
    agent: { name: "Morag Campbell", role: "Area Director", quote: "West End tenement flats are the most traded in Glasgow — they're rare, versatile and always in demand.", initials: "MC" },
    transportLinks: [
      { name: "Hillhead Subway", type: "underground", detail: "Glasgow Subway — 12 min to city centre", emoji: "🚇" },
      { name: "Partick Rail", type: "rail", detail: "ScotRail & Subway interchange", emoji: "🚆" },
    ],
  },
  "glasgow/merchant-city": {
    slug: "merchant-city",
    name: "Merchant City",
    citySlug: "glasgow",
    cityName: "Glasgow",
    borough: "Merchant City & Trongate",
    postcode: "G1",
    description: "Merchant City is Glasgow's fashionable historic core, where 18th-century tobacco merchants' warehouses have been converted into loft apartments, boutique hotels and award-winning restaurants. It is Glasgow's most urban neighbourhood, drawing professionals who want to live at the centre of everything.",
    coordinates: { lat: 55.8576, lng: -4.2432 },
    avgPrice: 250000,
    avgPriceFormatted: "£250,000",
    yoyChange: "+5.8%",
    greenSpace: "8%",
    walkability: "High",
    noiseLevel: "Busy",
    demographics: { topGroup: "Young Urban Professionals", medianAge: 30, ownerOccupied: 25, privateRented: 70, socialRented: 5, vibe: "Urban & design-led" },
    schools: [
      { name: "Trongate Primary School", ofsted: "Good", distance: "0.5 mi", type: "Primary" },
      { name: "Glasgow Academy", ofsted: "Outstanding", distance: "0.7 mi", type: "All-through" },
      { name: "St Mungo's Academy", ofsted: "Good", distance: "0.6 mi", type: "Secondary" },
    ],
    localFavourites: [
      { label: "Merchant Square", desc: "Victorian market building converted to bars and events space", category: "attraction" },
      { label: "Hutchesons", desc: "Grand dining room in a 19th-century almshouse", category: "cafe" },
      { label: "The Corinthian Club", desc: "Opulent converted bank with bars, dining and a casino", category: "pub" },
    ],
    propertyMix: { D: 0, S: 2, T: 5, F: 91, O: 2 },
    broadband: { download: 260, upload: 60, coverage5g: true },
    crimeIndex: { local: 110, borough: 92, city: 80 },
    agent: { name: "Rory Gallagher", role: "City Centre Specialist", quote: "Merchant City warehouse conversions attract a specific buyer — design-led, central, no compromise.", initials: "RG" },
    transportLinks: [
      { name: "Glasgow Queen Street", type: "rail", detail: "5 min walk to national rail hub", emoji: "🚆" },
      { name: "Argyle Street Rail", type: "rail", detail: "Low Level station — cross-city connections", emoji: "🚆" },
    ],
  },
  "glasgow/shawlands": {
    slug: "shawlands",
    name: "Shawlands",
    citySlug: "glasgow",
    cityName: "Glasgow",
    borough: "Pollokshields & Shawlands",
    postcode: "G41",
    description: "Shawlands is the south side's most vibrant high street neighbourhood, with an eclectic mix of independent traders, excellent brunch cafés and a strong community spirit. It attracts young families priced out of the West End and professionals seeking more space and better value south of the river.",
    coordinates: { lat: 55.8331, lng: -4.2810 },
    avgPrice: 265000,
    avgPriceFormatted: "£265,000",
    yoyChange: "+5.2%",
    greenSpace: "20%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Young Families & Professionals", medianAge: 34, ownerOccupied: 48, privateRented: 44, socialRented: 8, vibe: "South-side cool" },
    schools: [
      { name: "Shawlands Academy", ofsted: "Good", distance: "0.4 mi", type: "Secondary" },
      { name: "Pollok Primary School", ofsted: "Good", distance: "0.5 mi", type: "Primary" },
      { name: "Battlefield Primary School", ofsted: "Outstanding", distance: "0.6 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Pollok Country Park", desc: "360-acre park housing the Burrell Collection", category: "park" },
      { label: "Tchai-Ovna", desc: "Quirky tearoom beloved by Glasgow creatives", category: "cafe" },
      { label: "The Granary", desc: "Converted grain store bar with a huge outdoor terrace", category: "pub" },
    ],
    propertyMix: { D: 8, S: 14, T: 22, F: 54, O: 2 },
    broadband: { download: 200, upload: 42, coverage5g: true },
    crimeIndex: { local: 72, borough: 78, city: 80 },
    agent: { name: "Karen Leitch", role: "Sales Manager", quote: "Shawlands is Glasgow's new Byres Road — values have outperformed every south-side postcode for three years.", initials: "KL" },
    transportLinks: [
      { name: "Crossmyloof Rail", type: "rail", detail: "ScotRail — 12 min to Glasgow Central", emoji: "🚆" },
      { name: "Pollokshaws Road Bus", type: "bus", detail: "Routes 38/57 — frequent to city centre", emoji: "🚌" },
    ],
  },

  // Nottingham
  "nottingham/hockley": {
    slug: "hockley",
    name: "Hockley",
    citySlug: "nottingham",
    cityName: "Nottingham",
    borough: "Nottingham City Centre",
    postcode: "NG1",
    description: "Hockley is Nottingham's creative and independent quarter, a compact area of Victorian red-brick buildings housing independent boutiques, record shops, tattoo studios and craft bars. It is the heartbeat of the city's alternative culture and attracts young renters seeking an urban, characterful environment.",
    coordinates: { lat: 52.9548, lng: -1.1421 },
    avgPrice: 180000,
    avgPriceFormatted: "£180,000",
    yoyChange: "+6.5%",
    greenSpace: "8%",
    walkability: "High",
    noiseLevel: "Busy",
    demographics: { topGroup: "Students & Creatives", medianAge: 26, ownerOccupied: 15, privateRented: 80, socialRented: 5, vibe: "Alternative & independent" },
    schools: [
      { name: "St Ann's Well Academy", ofsted: "Good", distance: "0.6 mi", type: "Primary" },
      { name: "Nottingham Academy", ofsted: "Good", distance: "0.7 mi", type: "All-through" },
      { name: "Lees Hill Infant School", ofsted: "Good", distance: "0.5 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Pelham Street Murals", desc: "Rotating legal street art installations", category: "attraction" },
      { label: "Cartwheel Coffee", desc: "Award-winning speciality roastery and brew bar", category: "cafe" },
      { label: "The Alchemist", desc: "Theatrical cocktail bar with wizard-themed drinks", category: "pub" },
    ],
    propertyMix: { D: 0, S: 2, T: 10, F: 86, O: 2 },
    broadband: { download: 240, upload: 54, coverage5g: true },
    crimeIndex: { local: 115, borough: 95, city: 82 },
    agent: { name: "Tom Baines", role: "Urban Lettings", quote: "Hockley is pure yield play — 7–8% gross is achievable and tenants never struggle to find.", initials: "TB" },
    transportLinks: [
      { name: "Nottingham Rail", type: "rail", detail: "10 min walk to Nottingham station", emoji: "🚆" },
      { name: "Old Market Square Tram", type: "tram", detail: "Nottingham Express Transit — city-wide tram", emoji: "🚊" },
    ],
  },
  "nottingham/west-bridgford": {
    slug: "west-bridgford",
    name: "West Bridgford",
    citySlug: "nottingham",
    cityName: "Nottingham",
    borough: "Rushcliffe",
    postcode: "NG2",
    description: "West Bridgford is Nottingham's premier family suburb — a largely owner-occupier enclave with excellent schools, a thriving high street and Trent Bridge Cricket Ground at its heart. It consistently tops quality-of-life surveys for the East Midlands and is the destination of choice for professional families.",
    coordinates: { lat: 52.9285, lng: -1.1262 },
    avgPrice: 360000,
    avgPriceFormatted: "£360,000",
    yoyChange: "+3.8%",
    greenSpace: "32%",
    walkability: "Medium",
    noiseLevel: "Quiet",
    demographics: { topGroup: "Professional Families", medianAge: 42, ownerOccupied: 68, privateRented: 26, socialRented: 6, vibe: "Suburban & aspirational" },
    schools: [
      { name: "West Bridgford School", ofsted: "Outstanding", distance: "0.4 mi", type: "Secondary" },
      { name: "Greythorn Primary School", ofsted: "Outstanding", distance: "0.3 mi", type: "Primary" },
      { name: "Bridgford Road Infant School", ofsted: "Good", distance: "0.5 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Trent Bridge Cricket Ground", desc: "Test match venue with a superb county programme", category: "attraction" },
      { label: "Bridgford Deli", desc: "Award-winning deli at the heart of the high street", category: "shop" },
      { label: "The Poppy & Pint", desc: "Family-friendly pub with a great real ale selection", category: "pub" },
    ],
    propertyMix: { D: 30, S: 28, T: 24, F: 16, O: 2 },
    broadband: { download: 195, upload: 40, coverage5g: true },
    crimeIndex: { local: 30, borough: 40, city: 82 },
    agent: { name: "Claire Newton", role: "Director", quote: "West Bridgford is perpetually under-supplied — anything well-priced gets multiple offers.", initials: "CN" },
    transportLinks: [
      { name: "Nottingham Rail", type: "rail", detail: "Bus or tram to Nottingham station — 15 min", emoji: "🚆" },
      { name: "Compton Acres Tram", type: "tram", detail: "NET Tram — direct to city centre", emoji: "🚊" },
    ],
  },
  "nottingham/beeston": {
    slug: "beeston",
    name: "Beeston",
    citySlug: "nottingham",
    cityName: "Nottingham",
    borough: "Broxtowe",
    postcode: "NG9",
    description: "Beeston is Nottingham's best-value commuter suburb, a thriving town in its own right with strong independent traders, a busy market and proximity to both Nottingham University and the Queen's Medical Centre. The tram line has dramatically increased its attractiveness to professionals.",
    coordinates: { lat: 52.9262, lng: -1.2100 },
    avgPrice: 240000,
    avgPriceFormatted: "£240,000",
    yoyChange: "+5.0%",
    greenSpace: "20%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Young Families & University Staff", medianAge: 35, ownerOccupied: 55, privateRented: 38, socialRented: 7, vibe: "Unpretentious & community-led" },
    schools: [
      { name: "Beeston Fields Primary School", ofsted: "Outstanding", distance: "0.4 mi", type: "Primary" },
      { name: "The Alderman White School", ofsted: "Good", distance: "0.6 mi", type: "Secondary" },
      { name: "Round Hill Primary School", ofsted: "Good", distance: "0.5 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Attenborough Nature Reserve", desc: "Local nature reserve and SSSI on the River Trent", category: "park" },
      { label: "Beeston Market", desc: "Busy weekly market with local traders since medieval times", category: "shop" },
      { label: "The Victoria Hotel", desc: "Traditional free house with 40+ real ales on tap", category: "pub" },
    ],
    propertyMix: { D: 14, S: 20, T: 42, F: 22, O: 2 },
    broadband: { download: 190, upload: 38, coverage5g: false },
    crimeIndex: { local: 52, borough: 48, city: 82 },
    agent: { name: "Simon Ward", role: "Branch Manager", quote: "The tram changed everything for Beeston — it's now 12 minutes from the city centre by rail.", initials: "SW" },
    transportLinks: [
      { name: "Beeston Tram", type: "tram", detail: "NET — 12 min to Nottingham city centre", emoji: "🚊" },
      { name: "Beeston Rail", type: "rail", detail: "East Midlands Railway — direct to Derby", emoji: "🚆" },
    ],
  },

  // Sheffield
  "sheffield/kelham-island": {
    slug: "kelham-island",
    name: "Kelham Island",
    citySlug: "sheffield",
    cityName: "Sheffield",
    borough: "Sheffield City Centre & Kelham",
    postcode: "S3",
    description: "Kelham Island is Sheffield's most talked-about neighbourhood — a former industrial island in the River Don that has reinvented itself as a hub of craft beer, artisan food and warehouse living. The Kelham Island Museum preserves its steelmaking past while a wave of new residents transforms its future.",
    coordinates: { lat: 53.3928, lng: -1.4742 },
    avgPrice: 215000,
    avgPriceFormatted: "£215,000",
    yoyChange: "+7.5%",
    greenSpace: "10%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Young Professionals & Creatives", medianAge: 29, ownerOccupied: 22, privateRented: 74, socialRented: 4, vibe: "Industrial-cool & regenerating" },
    schools: [
      { name: "Netherthorpe Primary School", ofsted: "Good", distance: "0.5 mi", type: "Primary" },
      { name: "Parkwood Academy", ofsted: "Good", distance: "0.7 mi", type: "Secondary" },
      { name: "Sheffield Springs Academy", ofsted: "Good", distance: "0.8 mi", type: "All-through" },
    ],
    localFavourites: [
      { label: "Kelham Island Museum", desc: "Interactive industrial museum with a massive Bessemer converter", category: "attraction" },
      { label: "Peddler Market", desc: "Sheffield's street food collective in a Victorian courtyard", category: "cafe" },
      { label: "The Fat Cat", desc: "Landmark real-ale pub — birthplace of Sheffield craft brewing", category: "pub" },
    ],
    propertyMix: { D: 0, S: 2, T: 8, F: 88, O: 2 },
    broadband: { download: 245, upload: 56, coverage5g: true },
    crimeIndex: { local: 92, borough: 82, city: 75 },
    agent: { name: "Jack Delaney", role: "City Centre Lead", quote: "Kelham Island has the best capital growth story in South Yorkshire — and it's only half way through.", initials: "JD" },
    transportLinks: [
      { name: "Sheffield Rail", type: "rail", detail: "12 min walk to Sheffield station — London in 2h 8m", emoji: "🚆" },
      { name: "Penistone Road Tram", type: "tram", detail: "Supertram — direct to Sheffield city centre", emoji: "🚊" },
    ],
  },
  "sheffield/crookes": {
    slug: "crookes",
    name: "Crookes",
    citySlug: "sheffield",
    cityName: "Sheffield",
    borough: "Crookes & Crosspool",
    postcode: "S10",
    description: "Crookes is one of Sheffield's most popular residential neighbourhoods for young professionals and families, sitting above the city with commanding views. A charming local high street, good schools and affordable Victorian terraces make it consistently one of Sheffield's strongest sellers' markets.",
    coordinates: { lat: 53.3870, lng: -1.5028 },
    avgPrice: 270000,
    avgPriceFormatted: "£270,000",
    yoyChange: "+5.2%",
    greenSpace: "24%",
    walkability: "High",
    noiseLevel: "Moderate",
    demographics: { topGroup: "Young Professionals & Families", medianAge: 33, ownerOccupied: 52, privateRented: 42, socialRented: 6, vibe: "Friendly & neighbourhood-focused" },
    schools: [
      { name: "Tapton School", ofsted: "Outstanding", distance: "0.5 mi", type: "Secondary" },
      { name: "Lydgate Infant & Junior School", ofsted: "Outstanding", distance: "0.4 mi", type: "Primary" },
      { name: "St Thomas of Canterbury RC Primary", ofsted: "Good", distance: "0.6 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Rivelin Valley Park", desc: "Secluded valley walk with millponds and ancient woodland", category: "park" },
      { label: "Crookes Social Club", desc: "Iconic co-operative social club open to all", category: "pub" },
      { label: "Marmadukes Café Bar", desc: "Popular neighbourhood café with a loyal brunch following", category: "cafe" },
    ],
    propertyMix: { D: 8, S: 14, T: 56, F: 20, O: 2 },
    broadband: { download: 200, upload: 44, coverage5g: true },
    crimeIndex: { local: 58, borough: 70, city: 75 },
    agent: { name: "Emma Davenport", role: "Senior Valuer", quote: "Crookes terraces with parking are the most competed-for properties in Sheffield right now.", initials: "ED" },
    transportLinks: [
      { name: "Fulwood Tram", type: "tram", detail: "Supertram — 15 min to Sheffield city centre", emoji: "🚊" },
      { name: "Crookes Valley Road Bus", type: "bus", detail: "Route 52 — frequent to city centre", emoji: "🚌" },
    ],
  },
  "sheffield/ecclesall": {
    slug: "ecclesall",
    name: "Ecclesall",
    citySlug: "sheffield",
    cityName: "Sheffield",
    borough: "Ecclesall",
    postcode: "S11",
    description: "Ecclesall is Sheffield's most prestigious address, with large stone-built Edwardian and Victorian villas on leafy Ecclesall Road South. Home to the famous Abbeydale Road restaurant and bar strip, it attracts Sheffield's senior professional elite and is the city's most consistent price performer.",
    coordinates: { lat: 53.3636, lng: -1.5011 },
    avgPrice: 380000,
    avgPriceFormatted: "£380,000",
    yoyChange: "+3.5%",
    greenSpace: "40%",
    walkability: "Medium",
    noiseLevel: "Quiet",
    demographics: { topGroup: "Established Professionals", medianAge: 44, ownerOccupied: 65, privateRented: 28, socialRented: 7, vibe: "Affluent & refined" },
    schools: [
      { name: "Silverdale School", ofsted: "Outstanding", distance: "0.4 mi", type: "Secondary" },
      { name: "Ecclesall CE Infant School", ofsted: "Outstanding", distance: "0.3 mi", type: "Primary" },
      { name: "Dobcroft Infant School", ofsted: "Outstanding", distance: "0.5 mi", type: "Primary" },
    ],
    localFavourites: [
      { label: "Ecclesall Woods", desc: "Ancient woodland — Sheffield's largest and most loved green space", category: "park" },
      { label: "Forge Bakehouse", desc: "Artisan bakery using stone-milled organic flour", category: "cafe" },
      { label: "The Broadfield", desc: "Smart gastropub with an extensive wine list", category: "pub" },
    ],
    propertyMix: { D: 35, S: 28, T: 20, F: 15, O: 2 },
    broadband: { download: 195, upload: 40, coverage5g: true },
    crimeIndex: { local: 38, borough: 55, city: 75 },
    agent: { name: "Sarah Brooke", role: "Partner", quote: "Ecclesall Road South detacheds are Sheffield's equivalent of London's finest — they never languish.", initials: "SB" },
    transportLinks: [
      { name: "Banner Cross Tram", type: "tram", detail: "Supertram — 20 min to Sheffield city centre", emoji: "🚊" },
      { name: "Ecclesall Road Bus", type: "bus", detail: "Routes 81/82 — frequent to centre", emoji: "🚌" },
    ],
  },
};

export const NEIGHBOURHOODS = data;

export function getNeighbourhood(citySlug: string, areaSlug: string): NeighbourhoodData | null {
  return data[`${citySlug}/${areaSlug}`] ?? null;
}

export function getNeighbourhoodsForCity(citySlug: string): NeighbourhoodData[] {
  return Object.values(data).filter((n) => n.citySlug === citySlug);
}
