/* eslint-disable no-console -- TODO Sprint 1: migrate console.error to captureException */
/**
 * GET /api/market-map/sold/[z]/[x]/[y]
 *
 * Returns a Mapbox Vector Tile (protobuf, layer `sold_parcels`) for the z/x/y
 * tile, generated by the `market_map_sold_parcels_tile` RPC. This layer is
 * HIGH-ZOOM ONLY (z >= 14): below that the RPC has nothing to draw, so we skip
 * the DB round-trip entirely and return 204. Each feature bakes its sales
 * detail in, so the map popup needs no follow-up fetch.
 *
 * Path params:
 *   z  zoom level (0..22; tiles only served at z >= 14)
 *   x  tile column
 *   y  tile row (a ".mvt"/".pbf" extension is stripped if present)
 */

import { NextRequest } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { decodeByteaToBuffer } from "@/services/market-map/tile-service";

const MAX_ZOOM = 22;
const MIN_SOLD_ZOOM = 14;

/**
 * Parse a tile coordinate segment to an integer, stripping any file extension
 * (e.g. "660.mvt" -> 660). Returns null when the segment is not a clean int.
 */
function parseTileCoord(raw: string): number | null {
  const stripped = raw.split(".")[0];
  if (!/^-?\d+$/.test(stripped)) return null;
  const n = Number(stripped);
  return Number.isInteger(n) ? n : null;
}

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ z: string; x: string; y: string }> },
): Promise<Response> {
  const { z: zRaw, x: xRaw, y: yRaw } = await params;

  const z = parseTileCoord(zRaw);
  const x = parseTileCoord(xRaw);
  const y = parseTileCoord(yRaw);

  if (z === null || x === null || y === null) {
    return new Response("Invalid tile coordinates", { status: 400 });
  }

  if (z < 0 || z > MAX_ZOOM) {
    return new Response("Zoom out of range", { status: 400 });
  }

  // Tile column/row must fit within the 2^z grid for the requested zoom.
  const maxIndex = 2 ** z - 1;
  if (x < 0 || x > maxIndex || y < 0 || y > maxIndex) {
    return new Response("Tile coordinates out of range", { status: 400 });
  }

  // High-zoom only: no sold-parcel geometry exists below z=14, so short-circuit
  // before touching the DB.
  if (z < MIN_SOLD_ZOOM) {
    return new Response(null, { status: 204 });
  }

  const supabase = createAdminClient();
  const { data, error } = await supabase.rpc("market_map_sold_parcels_tile", {
    p_z: z,
    p_x: x,
    p_y: y,
  });

  if (error) {
    console.error("[market-map-sold] RPC error:", error);
    return new Response("Failed to generate tile", { status: 500 });
  }

  const buffer = decodeByteaToBuffer(typeof data === "string" ? data : null);
  if (buffer === null) {
    return new Response(null, { status: 204 });
  }

  // Buffer is a Uint8Array subclass; pass a plain view to satisfy the web
  // `BodyInit` type (the runtime streams the same bytes).
  return new Response(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/vnd.mapbox-vector-tile",
      "Cache-Control": "public, max-age=31536000, immutable",
    },
  });
}
