export type MockProperty = {
  id: string;
  slug: string;
  title: string;
  price: number;
  priceFormatted: string;
  listingType: "sale" | "rent" | "auction";
  address: { line1: string; line2: string; postcode: string };
  beds: number;
  baths: number;
  receptions: number;
  sqft: number;
  type: string;
  image: string;
  images: string[];
  description: string;
  features: string[];
  agent: { name: string; agency: string; phone: string; avatar: string };
  epc: string;
  tenure: string;
  councilTax: string;
  listedDate: string;
};

export const MOCK_PROPERTIES: MockProperty[] = [
  {
    id: "prop-1",
    slug: "14-elm-road-isleworth",
    title: "3 Bedroom Semi-Detached House",
    price: 425000,
    priceFormatted: "£425,000",
    listingType: "sale",
    address: { line1: "14 Elm Road", line2: "Isleworth, Middlesex", postcode: "TW7 4PQ" },
    beds: 3,
    baths: 2,
    receptions: 1,
    sqft: 1200,
    type: "Semi-Detached",
    image: "/images/properties/property-1.jpg",
    images: [
      "/images/properties/property-1.jpg",
      "/images/properties/property-2.jpg",
      "/images/properties/property-3.jpg",
      "/images/properties/property-4.jpg",
    ],
    description: "A beautifully presented three-bedroom semi-detached house in the heart of Isleworth. Featuring a recently refurbished kitchen, south-facing garden, and modern bathroom. Close to excellent schools and transport links. The property benefits from double glazing throughout and a new gas central heating system. Chain free.",
    features: ["South-facing garden", "Chain free", "Recently refurbished kitchen", "Double glazing", "Gas central heating", "Close to schools"],
    agent: { name: "James Wilson", agency: "Marsh & Parsons", phone: "020 7123 4567", avatar: "/images/agents/agent-1.jpg" },
    epc: "C",
    tenure: "Freehold",
    councilTax: "D",
    listedDate: "2026-02-20",
  },
  {
    id: "prop-2",
    slug: "22-oak-lane-richmond",
    title: "4 Bedroom Detached House",
    price: 850000,
    priceFormatted: "£850,000",
    listingType: "sale",
    address: { line1: "22 Oak Lane", line2: "Richmond, Surrey", postcode: "TW9 2AB" },
    beds: 4,
    baths: 3,
    receptions: 2,
    sqft: 2100,
    type: "Detached",
    image: "/images/properties/property-2.jpg",
    images: ["/images/properties/property-2.jpg", "/images/properties/property-3.jpg"],
    description: "A stunning four-bedroom detached house with large garden, double garage, and panoramic views across Richmond Park. Master bedroom with en-suite, open-plan kitchen/dining area, and home office. Recently renovated to a high standard.",
    features: ["Double garage", "Garden", "Richmond Park views", "Home office", "En-suite master", "Open-plan kitchen"],
    agent: { name: "Sarah Thompson", agency: "Knight Frank", phone: "020 7234 5678", avatar: "/images/agents/agent-2.jpg" },
    epc: "B",
    tenure: "Freehold",
    councilTax: "F",
    listedDate: "2026-03-01",
  },
  {
    id: "prop-3",
    slug: "flat-7-river-court-putney",
    title: "2 Bedroom Flat",
    price: 375000,
    priceFormatted: "£375,000",
    listingType: "sale",
    address: { line1: "Flat 7, River Court", line2: "Putney, London", postcode: "SW15 1QT" },
    beds: 2,
    baths: 1,
    receptions: 1,
    sqft: 750,
    type: "Flat",
    image: "/images/properties/property-3.jpg",
    images: ["/images/properties/property-3.jpg", "/images/properties/property-4.jpg"],
    description: "A bright and spacious two-bedroom flat overlooking the River Thames. Modern kitchen with integrated appliances, generous living room, and private balcony. Secure entry, lift access, and allocated parking space included.",
    features: ["River views", "Balcony", "Allocated parking", "Lift access", "Integrated appliances", "Secure entry"],
    agent: { name: "James Wilson", agency: "Marsh & Parsons", phone: "020 7123 4567", avatar: "/images/agents/agent-1.jpg" },
    epc: "B",
    tenure: "Leasehold",
    councilTax: "C",
    listedDate: "2026-02-15",
  },
  {
    id: "prop-4",
    slug: "the-old-rectory-burford",
    title: "5 Bedroom Country House",
    price: 1200000,
    priceFormatted: "£1,200,000",
    listingType: "sale",
    address: { line1: "The Old Rectory", line2: "Burford, Oxfordshire", postcode: "OX18 4RL" },
    beds: 5,
    baths: 3,
    receptions: 3,
    sqft: 3500,
    type: "Detached",
    image: "/images/properties/property-4.jpg",
    images: ["/images/properties/property-4.jpg", "/images/properties/property-1.jpg"],
    description: "A magnificent Grade II listed country house in the picturesque Cotswolds village of Burford. Period features throughout including original fireplaces, exposed beams, and stone floors. Extensive grounds with mature gardens, paddock, and stable block.",
    features: ["Grade II listed", "Period features", "Mature gardens", "Paddock", "Stable block", "Exposed beams"],
    agent: { name: "Emma Richards", agency: "Savills", phone: "01993 456789", avatar: "/images/agents/agent-3.jpg" },
    epc: "D",
    tenure: "Freehold",
    councilTax: "G",
    listedDate: "2026-01-28",
  },
  {
    id: "prop-5",
    slug: "12-maple-street-manchester",
    title: "3 Bedroom Terraced House",
    price: 285000,
    priceFormatted: "£285,000",
    listingType: "sale",
    address: { line1: "12 Maple Street", line2: "Didsbury, Manchester", postcode: "M20 6RT" },
    beds: 3,
    baths: 1,
    receptions: 2,
    sqft: 1050,
    type: "Terraced",
    image: "/images/properties/property-1.jpg",
    images: ["/images/properties/property-1.jpg"],
    description: "A charming Victorian terraced house in popular Didsbury. Original features complemented by modern updates. Close to village amenities, Didsbury Park, and excellent transport links to Manchester city centre.",
    features: ["Victorian features", "Close to village", "Near transport", "Bay windows", "Rear garden", "Cellar"],
    agent: { name: "Tom Bradley", agency: "Gascoigne Halman", phone: "0161 123 4567", avatar: "/images/agents/agent-1.jpg" },
    epc: "C",
    tenure: "Freehold",
    councilTax: "C",
    listedDate: "2026-03-05",
  },
  {
    id: "prop-6",
    slug: "apt-15-harbourside-bristol",
    title: "1 Bedroom Apartment",
    price: 1250,
    priceFormatted: "£1,250 pcm",
    listingType: "rent",
    address: { line1: "Apt 15, Harbourside", line2: "Bristol", postcode: "BS1 5TY" },
    beds: 1,
    baths: 1,
    receptions: 1,
    sqft: 550,
    type: "Flat",
    image: "/images/properties/property-3.jpg",
    images: ["/images/properties/property-3.jpg"],
    description: "A modern one-bedroom apartment in the heart of Bristol's Harbourside development. Open-plan living, floor-to-ceiling windows, and stunning harbour views. Gym and concierge included.",
    features: ["Harbour views", "Concierge", "Gym access", "Floor-to-ceiling windows", "Furnished", "Parking available"],
    agent: { name: "Sarah Thompson", agency: "Ocean", phone: "0117 234 5678", avatar: "/images/agents/agent-2.jpg" },
    epc: "A",
    tenure: "Leasehold",
    councilTax: "B",
    listedDate: "2026-03-07",
  },
  {
    id: "prop-7",
    slug: "6-willow-close-edinburgh",
    title: "4 Bedroom Detached Bungalow",
    price: 495000,
    priceFormatted: "£495,000",
    listingType: "sale",
    address: { line1: "6 Willow Close", line2: "Corstorphine, Edinburgh", postcode: "EH12 7PL" },
    beds: 4,
    baths: 2,
    receptions: 2,
    sqft: 1800,
    type: "Bungalow",
    image: "/images/properties/property-2.jpg",
    images: ["/images/properties/property-2.jpg"],
    description: "A spacious detached bungalow in the sought-after Corstorphine area. Accessible living on one level with four bedrooms, two bathrooms, and a large conservatory. Low-maintenance garden and driveway parking.",
    features: ["Single level", "Conservatory", "Driveway", "Low maintenance garden", "Accessible", "Close to zoo"],
    agent: { name: "Alistair McGregor", agency: "ESPC", phone: "0131 456 7890", avatar: "/images/agents/agent-3.jpg" },
    epc: "C",
    tenure: "Freehold",
    councilTax: "E",
    listedDate: "2026-02-10",
  },
  {
    id: "prop-8",
    slug: "cottage-lane-bath",
    title: "2 Bedroom Georgian Cottage",
    price: 525000,
    priceFormatted: "£525,000",
    listingType: "sale",
    address: { line1: "3 Cottage Lane", line2: "Widcombe, Bath", postcode: "BA2 4JR" },
    beds: 2,
    baths: 1,
    receptions: 1,
    sqft: 900,
    type: "Cottage",
    image: "/images/properties/property-4.jpg",
    images: ["/images/properties/property-4.jpg"],
    description: "A characterful Georgian cottage in the desirable Widcombe area. Stone exterior, sash windows, and original fireplaces. Courtyard garden with views towards Beechen Cliff. Walking distance to Bath city centre and train station.",
    features: ["Georgian character", "Stone exterior", "Sash windows", "Courtyard garden", "City views", "Walk to station"],
    agent: { name: "James Wilson", agency: "Carter Jonas", phone: "01225 789012", avatar: "/images/agents/agent-1.jpg" },
    epc: "D",
    tenure: "Freehold",
    councilTax: "D",
    listedDate: "2026-02-25",
  },
];
