"use client";

import { z } from "zod";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  PDFDownloadLink,
} from "@react-pdf/renderer";

export const arrearsLetterSchema = z.object({
  tenantName: z.string().min(1, "Tenant name is required"),
  tenantAddress: z.string().min(1, "Tenant address is required"),
  landlordName: z.string().min(1, "Landlord name is required"),
  landlordAddress: z.string().min(1, "Landlord address is required"),
  propertyAddress: z.string().min(1, "Property address is required"),
  arrearsAmount: z.number().positive("Arrears amount must be positive"),
  daysOverdue: z.number().int().positive("Days overdue must be positive"),
  date: z.string().min(1, "Date is required"),
});

export type ArrearsLetterData = z.infer<typeof arrearsLetterSchema>;

const styles = StyleSheet.create({
  page: { padding: 48, fontFamily: "Helvetica", fontSize: 11, lineHeight: 1.5, color: "#111827" },
  title: { fontSize: 14, fontFamily: "Helvetica-Bold", textAlign: "center", marginBottom: 24 },
  row: { flexDirection: "row", marginBottom: 6 },
  label: { fontFamily: "Helvetica-Bold", width: 160 },
  value: { flex: 1 },
  paragraph: { marginBottom: 12 },
  bold: { fontFamily: "Helvetica-Bold" },
  divider: { borderBottomWidth: 1, borderBottomColor: "#D1D5DB", marginVertical: 16 },
  footer: { marginTop: 32, fontSize: 9, color: "#6B7280" },
});

function ArrearsLetterDocument({ data }: Readonly<{ data: ArrearsLetterData }>) {
  const formattedAmount = new Intl.NumberFormat("en-GB", {
    style: "currency", currency: "GBP",
  }).format(data.arrearsAmount);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>FORMAL NOTICE OF RENT ARREARS</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Date:</Text>
          <Text style={styles.value}>{data.date}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>To:</Text>
          <Text style={styles.value}>{data.tenantName}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Address:</Text>
          <Text style={styles.value}>{data.tenantAddress}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Property:</Text>
          <Text style={styles.value}>{data.propertyAddress}</Text>
        </View>
        <View style={styles.divider} />
        <Text style={styles.paragraph}>Dear {data.tenantName},</Text>
        <Text style={styles.paragraph}>
          I am writing to inform you that your rent account is currently in arrears.
          The outstanding balance is <Text style={styles.bold}>{formattedAmount}</Text>,
          which has been overdue for <Text style={styles.bold}>{data.daysOverdue} days</Text>.
        </Text>
        <Text style={styles.paragraph}>
          Please arrange payment of the full amount as soon as possible. If you are
          experiencing financial difficulties, please contact me immediately so we
          can discuss a repayment plan.
        </Text>
        <Text style={styles.paragraph}>
          If payment is not received within 14 days of this letter, I may need to
          take further action, which could include formal possession proceedings.
        </Text>
        <Text style={styles.paragraph}>Yours sincerely,</Text>
        <Text style={{ marginTop: 24, fontFamily: "Helvetica-Bold" }}>{data.landlordName}</Text>
        <Text>{data.landlordAddress}</Text>
        <Text style={styles.footer}>
          Generated by Britestate on {data.date}. This letter does not constitute
          a legal notice under the Housing Act 1988.
        </Text>
      </Page>
    </Document>
  );
}

type ArrearsLetterPDFProps = Readonly<{
  data: ArrearsLetterData;
}>;

export function ArrearsLetterPDF({ data }: ArrearsLetterPDFProps) {
  const validation = arrearsLetterSchema.safeParse(data);

  if (!validation.success) {
    return (
      <p className="text-sm text-red-500">
        Cannot generate letter: {validation.error.errors[0].message}
      </p>
    );
  }

  return (
    <PDFDownloadLink
      document={<ArrearsLetterDocument data={validation.data} />}
      fileName={`arrears-letter-${data.tenantName.replace(/\s+/g, "-").toLowerCase()}.pdf`}
      className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700"
    >
      {({ loading }) => (loading ? "Generating..." : "Download Arrears Letter")}
    </PDFDownloadLink>
  );
}
