import { sendVerification } from "@/services/email/email-service";
import type { Tier1Action, Tier1ActionContext } from "./types";
import { Tier1ActionError } from "./types";

/**
 * Re-issue an email-confirmation link to a user who has not yet verified.
 *
 * Low risk, reversible (idempotent — re-running just sends another link). The
 * link is generated by Supabase and handed straight to the email service; it is
 * NEVER returned to the caller or written to the audit log. Delivery goes only
 * to the account's own address.
 */

type AuthUserLite = {
  id: string;
  email: string | null;
  emailConfirmed: boolean;
  firstName: string;
};

async function loadAuthUser(
  ctx: Tier1ActionContext,
): Promise<AuthUserLite> {
  const { data, error } = await ctx.supabase.auth.admin.getUserById(ctx.targetId);
  if (error || !data?.user) {
    throw new Tier1ActionError("User not found", 404);
  }
  const user = data.user;
  const metadata = (user.user_metadata ?? {}) as Record<string, unknown>;
  return {
    id: user.id,
    email: user.email ?? null,
    emailConfirmed: Boolean(user.email_confirmed_at),
    firstName: typeof metadata.first_name === "string" ? metadata.first_name : "",
  };
}

export const resendVerificationEmail: Tier1Action = {
  key: "resend-verification-email",
  label: "Resend verification email",
  description:
    "Send the user a fresh email-confirmation link. The link is delivered only to their account email; it is never displayed here.",
  requiredPermission: "manage_users",
  targetType: "user",
  risk: "low",
  reversible: true,

  async preview(ctx) {
    const user = await loadAuthUser(ctx);
    const blockers: string[] = [];
    if (!user.email) blockers.push("Account has no email address on file.");
    if (user.emailConfirmed) blockers.push("Email is already verified.");
    return {
      summary: user.email
        ? `Send a new confirmation link to the account email (ending …${user.email.slice(-4)}).`
        : "Cannot send — no email on file.",
      effects: ["Emails a fresh confirmation link to the account address."],
      reversible: true,
      requiresApproval: false,
      blockers,
    };
  },

  async execute(ctx) {
    const user = await loadAuthUser(ctx);
    if (!user.email) throw new Tier1ActionError("Account has no email address", 422);
    if (user.emailConfirmed) throw new Tier1ActionError("Email is already verified", 409);

    const { data, error } = await ctx.supabase.auth.admin.generateLink({
      type: "magiclink",
      email: user.email,
    });
    const actionLink = data?.properties?.action_link;
    if (error || !actionLink) {
      throw new Tier1ActionError("Failed to generate confirmation link", 502);
    }

    await sendVerification({
      userId: user.id,
      email: user.email,
      firstName: user.firstName,
      verificationUrl: actionLink,
    });

    // Deliberately no link / token in the returned summary.
    return { summary: "Confirmation link emailed to the account address." };
  },
};
