-- supabase/migrations/20260320000002_property_seed_data.sql
-- Seed: 5 buy + 2 rent properties so property detail pages resolve.
-- Slugs are auto-generated by trg_generate_listing_slug trigger.

DO $$
DECLARE
  v_user_id UUID;
  v_prop_id UUID;
  v_listing_id UUID;
BEGIN
  -- Use the first user as property owner (listings.user_id is required FK)
  SELECT id INTO v_user_id FROM auth.users LIMIT 1;
  IF v_user_id IS NULL THEN
    RAISE NOTICE 'No users found, skipping property seed';
    RETURN;
  END IF;

  -- Property 1: 12 Kensington Gardens, London (Sale)
  IF NOT EXISTS (SELECT 1 FROM properties WHERE address_line1 = '12 Kensington Gardens' AND city = 'London') THEN
    INSERT INTO properties (address_line1, city, county, postcode, property_type, bedrooms, bathrooms, reception_rooms, square_footage, title, description, epc_rating, tenure, new_build, coordinates)
    VALUES ('12 Kensington Gardens', 'London', 'Greater London', 'W8 4QU', 'detached', 4, 3.0, 2, 2800,
      'Stunning 4-Bed Victorian in Kensington',
      'A beautifully restored Victorian property with period features, modern kitchen, and private garden. Close to Kensington Palace and Hyde Park.',
      'B', 'freehold', false, ST_SetSRID(ST_MakePoint(-0.1278, 51.5074), 4326)::geography)
    RETURNING id INTO v_prop_id;

    INSERT INTO listings (property_id, user_id, listing_type, status, price)
    VALUES (v_prop_id, v_user_id, 'sale', 'active', 1250000)
    RETURNING id INTO v_listing_id;

    INSERT INTO property_media (listing_id, media_type, url, sort_order)
    VALUES (v_listing_id, 'image', '/images/properties/property-1.jpg', 0);
  END IF;

  -- Property 2: 8 Primrose Hill Road, London (Sale)
  IF NOT EXISTS (SELECT 1 FROM properties WHERE address_line1 = '8 Primrose Hill Road' AND city = 'London') THEN
    INSERT INTO properties (address_line1, city, county, postcode, property_type, bedrooms, bathrooms, reception_rooms, square_footage, title, description, epc_rating, tenure, new_build, coordinates)
    VALUES ('8 Primrose Hill Road', 'London', 'Greater London', 'NW1 8YD', 'semi_detached', 3, 2.0, 1, 1800,
      'Charming 3-Bed Semi in Primrose Hill',
      'Light-filled semi-detached home with garden, close to Regents Park and excellent schools. Recently refurbished throughout.',
      'C', 'freehold', false, ST_SetSRID(ST_MakePoint(-0.1604, 51.5392), 4326)::geography)
    RETURNING id INTO v_prop_id;

    INSERT INTO listings (property_id, user_id, listing_type, status, price)
    VALUES (v_prop_id, v_user_id, 'sale', 'active', 875000)
    RETURNING id INTO v_listing_id;

    INSERT INTO property_media (listing_id, media_type, url, sort_order)
    VALUES (v_listing_id, 'image', '/images/properties/property-2.jpg', 0);
  END IF;

  -- Property 3: 45 Hampstead Lane, London (Sale)
  IF NOT EXISTS (SELECT 1 FROM properties WHERE address_line1 = '45 Hampstead Lane' AND city = 'London') THEN
    INSERT INTO properties (address_line1, city, county, postcode, property_type, bedrooms, bathrooms, reception_rooms, square_footage, title, description, epc_rating, tenure, new_build, coordinates)
    VALUES ('45 Hampstead Lane', 'London', 'Greater London', 'NW3 2QA', 'detached', 5, 4.0, 3, 3500,
      'Grand 5-Bed Detached in Hampstead',
      'Impressive family home with landscaped gardens, wine cellar, and home office. Walking distance to Hampstead Heath.',
      'B', 'freehold', false, ST_SetSRID(ST_MakePoint(-0.1735, 51.5615), 4326)::geography)
    RETURNING id INTO v_prop_id;

    INSERT INTO listings (property_id, user_id, listing_type, status, price)
    VALUES (v_prop_id, v_user_id, 'sale', 'active', 2100000)
    RETURNING id INTO v_listing_id;

    INSERT INTO property_media (listing_id, media_type, url, sort_order)
    VALUES (v_listing_id, 'image', '/images/properties/property-3.jpg', 0);
  END IF;

  -- Property 4: 22 Richmond Terrace, London (Sale)
  IF NOT EXISTS (SELECT 1 FROM properties WHERE address_line1 = '22 Richmond Terrace' AND city = 'London') THEN
    INSERT INTO properties (address_line1, city, county, postcode, property_type, bedrooms, bathrooms, reception_rooms, square_footage, title, description, epc_rating, tenure, new_build, coordinates)
    VALUES ('22 Richmond Terrace', 'London', 'Greater London', 'TW9 1HJ', 'terraced', 3, 2.0, 1, 1600,
      'Elegant 3-Bed Terrace near Richmond Green',
      'Period terraced house with original features, updated kitchen, and south-facing courtyard. Minutes from Richmond station.',
      'C', 'leasehold', false, ST_SetSRID(ST_MakePoint(-0.3037, 51.4613), 4326)::geography)
    RETURNING id INTO v_prop_id;

    INSERT INTO listings (property_id, user_id, listing_type, status, price)
    VALUES (v_prop_id, v_user_id, 'sale', 'active', 725000)
    RETURNING id INTO v_listing_id;

    INSERT INTO property_media (listing_id, media_type, url, sort_order)
    VALUES (v_listing_id, 'image', '/images/properties/property-4.jpg', 0);
  END IF;

  -- Property 5: 15 Islington High Street, London (Sale)
  IF NOT EXISTS (SELECT 1 FROM properties WHERE address_line1 = '15 Islington High Street' AND city = 'London') THEN
    INSERT INTO properties (address_line1, city, county, postcode, property_type, bedrooms, bathrooms, reception_rooms, square_footage, title, description, epc_rating, tenure, new_build, coordinates)
    VALUES ('15 Islington High Street', 'London', 'Greater London', 'N1 9LQ', 'flat', 2, 1.0, 1, 850,
      'Modern 2-Bed Flat in Angel Islington',
      'Stylish apartment with open-plan living, balcony views, and excellent transport links. Chain free.',
      'B', 'leasehold', false, ST_SetSRID(ST_MakePoint(-0.1030, 51.5362), 4326)::geography)
    RETURNING id INTO v_prop_id;

    INSERT INTO listings (property_id, user_id, listing_type, status, price)
    VALUES (v_prop_id, v_user_id, 'sale', 'active', 495000)
    RETURNING id INTO v_listing_id;

    INSERT INTO property_media (listing_id, media_type, url, sort_order)
    VALUES (v_listing_id, 'image', '/images/properties/property-5.jpg', 0);
  END IF;

  -- Rental 1: 3 Camden Passage, London (Rent)
  IF NOT EXISTS (SELECT 1 FROM properties WHERE address_line1 = '3 Camden Passage' AND city = 'London') THEN
    INSERT INTO properties (address_line1, city, county, postcode, property_type, bedrooms, bathrooms, reception_rooms, square_footage, title, description, epc_rating, new_build, coordinates)
    VALUES ('3 Camden Passage', 'London', 'Greater London', 'N1 8EA', 'flat', 1, 1.0, 1, 550,
      'Cosy 1-Bed Flat in Angel',
      'Well-maintained flat with modern finishes, perfect for young professionals. Bills not included.',
      'C', false, ST_SetSRID(ST_MakePoint(-0.1060, 51.5345), 4326)::geography)
    RETURNING id INTO v_prop_id;

    INSERT INTO listings (property_id, user_id, listing_type, status, price, rent_frequency)
    VALUES (v_prop_id, v_user_id, 'rent', 'active', 1800, 'monthly')
    RETURNING id INTO v_listing_id;

    INSERT INTO property_media (listing_id, media_type, url, sort_order)
    VALUES (v_listing_id, 'image', '/images/properties/property-1.jpg', 0);
  END IF;

  -- Rental 2: 7 Shoreditch High Street, London (Rent)
  IF NOT EXISTS (SELECT 1 FROM properties WHERE address_line1 = '7 Shoreditch High Street' AND city = 'London') THEN
    INSERT INTO properties (address_line1, city, county, postcode, property_type, bedrooms, bathrooms, reception_rooms, square_footage, title, description, epc_rating, new_build, coordinates)
    VALUES ('7 Shoreditch High Street', 'London', 'Greater London', 'E1 6JE', 'flat', 2, 1.0, 1, 750,
      'Trendy 2-Bed in Shoreditch',
      'Industrial-chic apartment in the heart of Shoreditch with rooftop access. Furnished.',
      'B', false, ST_SetSRID(ST_MakePoint(-0.0776, 51.5232), 4326)::geography)
    RETURNING id INTO v_prop_id;

    INSERT INTO listings (property_id, user_id, listing_type, status, price, rent_frequency)
    VALUES (v_prop_id, v_user_id, 'rent', 'active', 2200, 'monthly')
    RETURNING id INTO v_listing_id;

    INSERT INTO property_media (listing_id, media_type, url, sort_order)
    VALUES (v_listing_id, 'image', '/images/properties/property-2.jpg', 0);
  END IF;

END
$$;
